# Stubs for tensorflow.python.ops.cond_v2_impl (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.core.framework import attr_value_pb2 as attr_value_pb2
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_util as control_flow_util, gen_functional_ops as gen_functional_ops
from typing import Any as Any

def cond_v2(pred: Any, true_fn: Any, false_fn: Any, name: str = ...): ...
