# Stubs for tensorflow.python.ops.cond_v2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.eager import function as function
from tensorflow.python.framework import function_def_to_graph as function_def_to_graph
from tensorflow.python.ops import gradients_impl as gradients_impl
from tensorflow.python.ops.cond_v2_impl import cond_v2 as cond_v2
