# Stubs for tensorflow.python.ops.confusion_matrix (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, ops as ops, sparse_tensor as sparse_tensor
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, control_flow_ops as control_flow_ops, math_ops as math_ops, sparse_ops as sparse_ops
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def remove_squeezable_dimensions(labels: Any, predictions: Any, expected_rank_diff: int = ..., name: Optional[Any] = ...): ...
def confusion_matrix(labels: Any, predictions: Any, num_classes: Optional[Any] = ..., dtype: Any = ..., name: Optional[Any] = ..., weights: Optional[Any] = ...): ...
