# Stubs for tensorflow.python.ops.ctc_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops, sparse_tensor as sparse_tensor
from tensorflow.python.ops import array_ops as array_ops, gen_ctc_ops as gen_ctc_ops
from tensorflow.python.ops.nn_grad import _BroadcastMul as _BroadcastMul
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

def ctc_loss(labels: Any, inputs: Any, sequence_length: Any, preprocess_collapse_repeated: bool = ..., ctc_merge_repeated: bool = ..., ignore_longer_outputs_than_inputs: bool = ..., time_major: bool = ...): ...
def ctc_greedy_decoder(inputs: Any, sequence_length: Any, merge_repeated: bool = ...): ...
def ctc_beam_search_decoder(inputs: Any, sequence_length: Any, beam_width: int = ..., top_paths: int = ..., merge_repeated: bool = ...): ...
