# Stubs for tensorflow.python.ops.cudnn_rnn_grad (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import gen_cudnn_rnn_ops as gen_cudnn_rnn_ops
