# Stubs for tensorflow.python.ops.gradients (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.eager import function as function
from tensorflow.python.eager.backprop import GradientTape as GradientTape
from tensorflow.python.ops.custom_gradient import custom_gradient as custom_gradient
from tensorflow.python.ops.gradients_impl import AggregationMethod as AggregationMethod, gradients as gradients, hessians as hessians
