# Stubs for tensorflow.python.ops.random_grad (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, gen_random_ops as gen_random_ops, math_ops as math_ops
from typing import Any as Any

def add_leading_unit_dimensions(x: Any, num_dimensions: Any): ...
