# Stubs for tensorflow.python.ops.spectral_ops_test_util (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.platform import test as test

def fft_kernel_label_map(): ...
