# Stubs for tensorflow.python.ops.summary_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops.gen_logging_ops import *
from tensorflow.core.framework import summary_pb2 as summary_pb2
from tensorflow.python.framework import constant_op as constant_op, ops as ops
from tensorflow.python.ops import gen_logging_ops as gen_logging_ops, summary_op_util as summary_op_util
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def tensor_summary(name: Any, tensor: Any, summary_description: Optional[Any] = ..., collections: Optional[Any] = ..., summary_metadata: Optional[Any] = ..., family: Optional[Any] = ..., display_name: Optional[Any] = ...): ...
