# Stubs for tensorflow.saved_model.builder (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.saved_model.builder import SavedModelBuilder as SavedModelBuilder
