# Stubs for tensorflow.python.data.util.random_seed (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops, random_seed as random_seed
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops
from typing import Any as Any

def get_seed(seed: Any): ...
