# Stubs for tensorflow.python.autograph.converters.decorators (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.autograph.core import converter as converter
from tensorflow.python.autograph.pyct import anno as anno
from tensorflow.python.util import tf_inspect as tf_inspect
from typing import Any as Any

class DecoratorsTransformer(converter.Base):
    def visit_FunctionDef(self, node: Any): ...

def transform(node: Any, ctx: Any): ...
