# Stubs for tensorflow.python.autograph.converters.directives (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.autograph.core import converter as converter
from tensorflow.python.autograph.lang import directives as directives
from tensorflow.python.autograph.pyct import anno as anno
from tensorflow.python.util import tf_inspect as tf_inspect
from typing import Any as Any

ENCLOSING_LOOP: str

class DirectivesTransformer(converter.Base):
    def visit_Expr(self, node: Any): ...
    def visit_While(self, node: Any): ...
    def visit_For(self, node: Any): ...

def transform(node: Any, ctx: Any): ...
