# Stubs for tensorflow.python.autograph.converters.slices (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.autograph.core import converter as converter
from tensorflow.python.autograph.lang import directives as directives
from tensorflow.python.autograph.pyct import templates as templates
from typing import Any as Any

class SliceTransformer(converter.Base):
    def visit_Assign(self, node: Any): ...
    def visit_Subscript(self, node: Any): ...

def transform(node: Any, ctx: Any): ...
