# Stubs for tensorflow._api.v1.keras.wrappers.scikit_learn (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.wrappers.scikit_learn import KerasClassifier as KerasClassifier, KerasRegressor as KerasRegressor
