# Stubs for tensorflow.contrib.gan.python.features.python.clip_weights (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.gan.python.features.python.clip_weights_impl import *
from tensorflow.contrib.gan.python.features.python import clip_weights_impl as clip_weights_impl
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented

# Names in __all__ with no definition:
#   VBN
#   clip_discriminator_weights
#   clip_variables
#   condition_tensor
#   condition_tensor_from_onehot
#   tensor_pool
