# Stubs for tensorflow._api.v1.dtypes (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python import DType as DType, as_dtype as as_dtype, as_string as as_string, cast as cast, complex as complex, saturate_cast as saturate_cast
