# Stubs for tensorflow.python.framework.graph_io (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.lib.io import file_io as file_io
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

def write_graph(graph_or_graph_def: Any, logdir: Any, name: Any, as_text: bool = ...): ...
