# Stubs for tensorflow.python.framework.load_library (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.core.framework import op_def_pb2 as op_def_pb2
from tensorflow.core.lib.core import error_codes_pb2 as error_codes_pb2
from tensorflow.python.lib.io import file_io as file_io
from tensorflow.python.util import compat as compat
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

def load_op_library(library_filename: Any): ...
def load_file_system_library(library_filename: Any) -> None: ...
def load_library(library_location: Any) -> None: ...
