# Stubs for tensorflow.python.framework.versions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python import pywrap_tensorflow as pywrap_tensorflow
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

__git_version__: Any
__compiler_version__: Any
__cxx11_abi_flag__: Any
__monolithic_build__: Any
VERSION: Any
GIT_VERSION = __git_version__
COMPILER_VERSION = __compiler_version__
CXX11_ABI_FLAG = __cxx11_abi_flag__
MONOLITHIC_BUILD = __monolithic_build__
GRAPH_DEF_VERSION: Any
GRAPH_DEF_VERSION_MIN_CONSUMER: Any
GRAPH_DEF_VERSION_MIN_PRODUCER: Any

# Names in __all__ with no definition:
#   __version__
