# Stubs for tensorflow.python.data.experimental.ops.counter (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.experimental.ops import scan_ops as scan_ops
from tensorflow.python.data.ops import dataset_ops as dataset_ops
from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

def Counter(start: int = ..., step: int = ..., dtype: Any = ...): ...
