# Stubs for tensorflow.python.data.experimental.ops.map_defun (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops, tensor_shape as tensor_shape
from tensorflow.python.ops import gen_dataset_ops as gen_dataset_ops
from typing import Any as Any

def map_defun(fn: Any, elems: Any, output_dtypes: Any, output_shapes: Any): ...
