# Stubs for tensorflow.python.data.experimental.ops.threadpool (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.ops import dataset_ops as dataset_ops
from tensorflow.python.eager import context as context
from tensorflow.python.ops import resource_variable_ops as resource_variable_ops
from typing import Any as Any, Optional as Optional

class PrivateThreadPool:
    def __init__(self, num_threads: Any, display_name: Optional[Any] = ..., max_intra_op_parallelism: int = ...) -> None: ...

class _ThreadPoolDataset(dataset_ops.UnaryDataset):
    def __init__(self, input_dataset: Any, thread_pool: Any) -> None: ...
    @property
    def output_shapes(self): ...
    @property
    def output_types(self): ...
    @property
    def output_classes(self): ...

def override_threadpool(dataset: Any, thread_pool: Any): ...
