# Stubs for tensorflow.contrib.signal.python.ops.shape_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.signal.python.ops import util_ops as util_ops
from tensorflow.python.framework import ops as ops, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops
from typing import Any as Any, Optional as Optional

def frame(signal: Any, frame_length: Any, frame_step: Any, pad_end: bool = ..., pad_value: int = ..., axis: int = ..., name: Optional[Any] = ...): ...
