# Stubs for tensorflow.contrib.signal.python.ops.spectral_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.signal.python.ops import reconstruction_ops as reconstruction_ops, shape_ops as shape_ops, window_ops as window_ops
from tensorflow.python.framework import constant_op as constant_op, ops as ops, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops, spectral_ops as spectral_ops
from typing import Any as Any, Optional as Optional

def stft(signals: Any, frame_length: Any, frame_step: Any, fft_length: Optional[Any] = ..., window_fn: Any = ..., pad_end: bool = ..., name: Optional[Any] = ...): ...
def inverse_stft_window_fn(frame_step: Any, forward_window_fn: Any = ..., name: Optional[Any] = ...): ...
def inverse_stft(stfts: Any, frame_length: Any, frame_step: Any, fft_length: Optional[Any] = ..., window_fn: Any = ..., name: Optional[Any] = ...): ...
