# Stubs for tensorflow.contrib.signal.python.ops.window_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, math_ops as math_ops
from typing import Any as Any, Optional as Optional

def hann_window(window_length: Any, periodic: bool = ..., dtype: Any = ..., name: Optional[Any] = ...): ...
def hamming_window(window_length: Any, periodic: bool = ..., dtype: Any = ..., name: Optional[Any] = ...): ...
