# Stubs for tensorflow.contrib.tpu.python.tpu.training_loop (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.tpu.python.tpu import tpu_function as tpu_function
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops
from typing import Any as Any, Optional as Optional

def while_loop(condition: Any, body: Any, inputs: Optional[Any] = ..., infeed_queue: Optional[Any] = ..., name: Optional[Any] = ...): ...
def repeat(n: Any, body: Any, inputs: Optional[Any] = ..., infeed_queue: Optional[Any] = ..., name: Optional[Any] = ...): ...
