# Stubs for tensorflow.contrib.tpu.python.tpu.util (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

def check_positive_integer(value: Any, name: Any) -> None: ...
