# Stubs for tensorflow.contrib.distribute (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.distribute.python.cross_tower_ops import *
from tensorflow.contrib.distribute.python.step_fn import *
from tensorflow.python.training.distribute import *
from tensorflow.python.training.distribution_strategy_context import *
from tensorflow.contrib.distribute.python.collective_all_reduce_strategy import CollectiveAllReduceStrategy as CollectiveAllReduceStrategy
from tensorflow.contrib.distribute.python.mirrored_strategy import MirroredStrategy as MirroredStrategy
from tensorflow.contrib.distribute.python.monitor import Monitor as Monitor
from tensorflow.contrib.distribute.python.one_device_strategy import OneDeviceStrategy as OneDeviceStrategy
from tensorflow.contrib.distribute.python.parameter_server_strategy import ParameterServerStrategy as ParameterServerStrategy
from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy as TPUStrategy
from tensorflow.python.distribute.distribute_config import DistributeConfig as DistributeConfig
from tensorflow.python.distribute.distribute_coordinator import run_standard_tensorflow_server as run_standard_tensorflow_server
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
