# Stubs for tensorflow._api.v1.graph_util (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python import import_graph_def as import_graph_def
from tensorflow.python.framework.graph_util import convert_variables_to_constants as convert_variables_to_constants, extract_sub_graph as extract_sub_graph, must_run_on_cpu as must_run_on_cpu, remove_training_nodes as remove_training_nodes, tensor_shape_from_node_def_name as tensor_shape_from_node_def_name
