# Stubs for tensorflow.contrib.boosted_trees.proto.split_info_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
SplitInfo: Any
ObliviousSplitInfo: Any
