# Stubs for tensorflow.tools.dist_test.server.grpc_tensorflow_server (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.core.protobuf import config_pb2 as config_pb2, tensorflow_server_pb2 as tensorflow_server_pb2
from tensorflow.python.platform import app as app
from tensorflow.python.training import server_lib as server_lib
from typing import Any as Any

def parse_cluster_spec(cluster_spec: Any, cluster: Any, verbose: bool = ...) -> None: ...
def main(unused_args: Any) -> None: ...
