# Stubs for tensorflow.contrib.stat_summarizer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.pywrap_tensorflow import DeleteStatSummarizer as DeleteStatSummarizer, NewStatSummarizer as NewStatSummarizer, StatSummarizer as StatSummarizer
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
