# Stubs for tensorflow.contrib.reduce_slice_ops.python.ops.reduce_slice_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.reduce_slice_ops.ops import gen_reduce_slice_ops as gen_reduce_slice_ops
from tensorflow.contrib.util import loader as loader
from tensorflow.python.platform import resource_loader as resource_loader

reduce_slice_sum = gen_reduce_slice_ops.reduce_slice_sum
reduce_slice_prod = gen_reduce_slice_ops.reduce_slice_prod
reduce_slice_max = gen_reduce_slice_ops.reduce_slice_max
reduce_slice_min = gen_reduce_slice_ops.reduce_slice_min
