# Stubs for tensorflow.contrib.lite.python.lite_constants (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
from typing import Any as Any

FLOAT: Any
INT32: Any
INT64: Any
STRING: Any
QUANTIZED_UINT8: Any
TENSORFLOW_GRAPHDEF: Any
TFLITE: Any
GRAPHVIZ_DOT: Any
EXPERIMENTAL_USE_TOCO_API_DIRECTLY: bool
