# Stubs for tensorflow.contrib.lite.python.tflite_convert (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.lite.python import lite as lite, lite_constants as lite_constants
from tensorflow.python.platform import app as app
from typing import Any as Any

def run_main(_: Any) -> None: ...
def main() -> None: ...
