# Stubs for tensorflow.python.estimator.gc (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from collections import namedtuple as namedtuple
from tensorflow.python.platform import gfile as gfile
from tensorflow.python.util import compat as compat

Path = namedtuple('Path', 'path export_version')
