# Stubs for tensorflow.keras.preprocessing.sequence (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.preprocessing.sequence import TimeseriesGenerator as TimeseriesGenerator, make_sampling_table as make_sampling_table, pad_sequences as pad_sequences, skipgrams as skipgrams
