# Stubs for tensorflow.python.ops.bitwise_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops.gen_bitwise_ops import *
from tensorflow.python.framework import ops as ops
