# Stubs for tensorflow.python.ops.custom_gradient (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.eager import backprop as backprop, context as context
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, gen_array_ops as gen_array_ops, resource_variable_ops as resource_variable_ops, variable_scope as variable_scope
from tensorflow.python.util import nest as nest, tf_decorator as tf_decorator, tf_inspect as tf_inspect
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

def custom_gradient(f: Any): ...
