# Stubs for tensorflow.python.ops.gen_user_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def fact(name: Optional[Any] = ...): ...
def fact_eager_fallback(name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...
