# Stubs for tensorflow.python.ops.image_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops.gen_image_ops import *
from tensorflow.python.ops.image_ops_impl import *
from tensorflow.python.ops.image_ops_impl import _Check3DImage as _Check3DImage, _ImageDimensions as _ImageDimensions
