# Stubs for tensorflow.python.ops.initializers_ns (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops import init_ops as init_ops, variables as _variables
from typing import Any as Any

zeros: Any
ones: Any
constant: Any
random_uniform: Any
random_normal: Any
truncated_normal: Any
uniform_unit_scaling: Any
variance_scaling: Any
orthogonal: Any
identity: Any
variables = _variables.variables_initializer
global_variables = _variables.global_variables_initializer
local_variables = _variables.local_variables_initializer
