# Stubs for tensorflow.python.ops.manip_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util import deprecation as deprecation
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

def roll(input: Any, shift: Any, axis: Any): ...
