# Stubs for tensorflow.python.ops.manip_grad (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import manip_ops as manip_ops
