# Stubs for tensorflow.python.ops.sparse_grad (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops, sparse_tensor as sparse_tensor
from tensorflow.python.ops import array_ops as array_ops, gen_sparse_ops as gen_sparse_ops, math_ops as math_ops, sparse_ops as sparse_ops
