# Stubs for tensorflow.python.ops.special_math_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops
from tensorflow.python.util import deprecation as deprecation
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def lbeta(x: Any, name: Optional[Any] = ...): ...
def bessel_i0(x: Any, name: Optional[Any] = ...): ...
def bessel_i1(x: Any, name: Optional[Any] = ...): ...
def einsum(equation: Any, *inputs: Any, **kwargs: Any): ...
