# Stubs for tensorflow.python.ops.tensor_array_grad (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import tensor_array_ops as tensor_array_ops
