# Stubs for tensorflow.contrib.input_pipeline (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.input_pipeline.python.ops.input_pipeline_ops import obtain_next as obtain_next
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
