# Stubs for tensorflow.python.autograph.core.function_wrapping (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from typing import Any as Any

def function_scope(function_name: Any) -> None: ...
