# Stubs for tensorflow.contrib.batching.python.ops.batch_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops.gen_batch_ops import *
from tensorflow.python.framework import function as function, ops as ops
from tensorflow.python.ops import gen_batch_ops as gen_batch_ops
from typing import Any as Any, Optional as Optional

def batch_function(num_batch_threads: Any, max_batch_size: Any, batch_timeout_micros: Any, allowed_batch_sizes: Optional[Any] = ..., max_enqueued_batches: int = ...): ...
def batch_function_v1(num_batch_threads: Any, max_batch_size: Any, batch_timeout_micros: Any, allowed_batch_sizes: Optional[Any] = ..., grad_timeout_micros: Any = ..., unbatch_timeout_micros: Any = ..., max_enqueued_batches: int = ...): ...
