# Stubs for tensorflow.python.data.experimental (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.experimental.ops.batching import dense_to_sparse_batch as dense_to_sparse_batch, map_and_batch as map_and_batch, unbatch as unbatch
from tensorflow.python.data.experimental.ops.counter import Counter as Counter
from tensorflow.python.data.experimental.ops.enumerate_ops import enumerate_dataset as enumerate_dataset
from tensorflow.python.data.experimental.ops.error_ops import ignore_errors as ignore_errors
from tensorflow.python.data.experimental.ops.get_single_element import get_single_element as get_single_element
from tensorflow.python.data.experimental.ops.grouping import Reducer as Reducer, bucket_by_sequence_length as bucket_by_sequence_length, group_by_reducer as group_by_reducer, group_by_window as group_by_window
from tensorflow.python.data.experimental.ops.interleave_ops import choose_from_datasets as choose_from_datasets, parallel_interleave as parallel_interleave, sample_from_datasets as sample_from_datasets
from tensorflow.python.data.experimental.ops.iterator_ops import CheckpointInputPipelineHook as CheckpointInputPipelineHook, make_saveable_from_iterator as make_saveable_from_iterator
from tensorflow.python.data.experimental.ops.optimization import AUTOTUNE as AUTOTUNE
from tensorflow.python.data.experimental.ops.parsing_ops import parse_example_dataset as parse_example_dataset
from tensorflow.python.data.experimental.ops.prefetching_ops import copy_to_device as copy_to_device, prefetch_to_device as prefetch_to_device
from tensorflow.python.data.experimental.ops.random_ops import RandomDataset as RandomDataset
from tensorflow.python.data.experimental.ops.readers import CsvDataset as CsvDataset, SqlDataset as SqlDataset, make_batched_features_dataset as make_batched_features_dataset, make_csv_dataset as make_csv_dataset
from tensorflow.python.data.experimental.ops.resampling import rejection_resample as rejection_resample
from tensorflow.python.data.experimental.ops.scan_ops import scan as scan
from tensorflow.python.data.experimental.ops.shuffle_ops import shuffle_and_repeat as shuffle_and_repeat
from tensorflow.python.data.experimental.ops.stats_ops import StatsAggregator as StatsAggregator, latency_stats as latency_stats, set_stats_aggregator as set_stats_aggregator
from tensorflow.python.data.experimental.ops.unique import unique as unique
from tensorflow.python.data.experimental.ops.writers import TFRecordWriter as TFRecordWriter
from tensorflow.python.data.ops.iterator_ops import get_next_as_optional as get_next_as_optional
from tensorflow.python.data.ops.optional_ops import Optional as Optional
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
