# Stubs for tensorflow.contrib.image.ops.gen_single_image_random_dot_stereograms_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def single_image_random_dot_stereograms(depth_values: Any, hidden_surface_removal: bool = ..., convergence_dots_size: int = ..., dots_per_inch: int = ..., eye_separation: float = ..., mu: float = ..., normalize: bool = ..., normalize_max: int = ..., normalize_min: int = ..., border_level: int = ..., number_colors: int = ..., output_image_shape: Any = ..., output_data_window: Any = ..., name: Optional[Any] = ...): ...
def single_image_random_dot_stereograms_eager_fallback(depth_values: Any, hidden_surface_removal: bool = ..., convergence_dots_size: int = ..., dots_per_inch: int = ..., eye_separation: float = ..., mu: float = ..., normalize: bool = ..., normalize_max: int = ..., normalize_min: int = ..., border_level: int = ..., number_colors: int = ..., output_image_shape: Any = ..., output_data_window: Any = ..., name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...
