# Stubs for tensorflow.contrib.image.ops.gen_distort_image_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def adjust_hsv_in_yiq(images: Any, delta_h: Any, scale_s: Any, scale_v: Any, name: Optional[Any] = ...): ...
def adjust_hsv_in_yiq_eager_fallback(images: Any, delta_h: Any, scale_s: Any, scale_v: Any, name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...
