# Stubs for tensorflow.random (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python import get_seed as get_seed, multinomial as multinomial, set_random_seed as set_random_seed, truncated_normal as truncated_normal
from tensorflow.python.ops.candidate_sampling_ops import log_uniform_candidate_sampler as log_uniform_candidate_sampler, uniform_candidate_sampler as uniform_candidate_sampler
from tensorflow.python.ops.random_ops import random_uniform as uniform