# Stubs for tensorflow.contrib.rnn.ops.gen_gru_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from collections import namedtuple as namedtuple
from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

# _GRUBlockCellOutput = namedtuple('GRUBlockCell', <ERROR>)

def gru_block_cell(x: Any, h_prev: Any, w_ru: Any, w_c: Any, b_ru: Any, b_c: Any, name: Optional[Any] = ...): ...
def gru_block_cell_eager_fallback(x: Any, h_prev: Any, w_ru: Any, w_c: Any, b_ru: Any, b_c: Any, name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...

# _GRUBlockCellGradOutput = namedtuple('GRUBlockCellGrad', <ERROR>)

def gru_block_cell_grad(x: Any, h_prev: Any, w_ru: Any, w_c: Any, b_ru: Any, b_c: Any, r: Any, u: Any, c: Any, d_h: Any, name: Optional[Any] = ...): ...
def gru_block_cell_grad_eager_fallback(x: Any, h_prev: Any, w_ru: Any, w_c: Any, b_ru: Any, b_c: Any, r: Any, u: Any, c: Any, d_h: Any, name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...
