# Stubs for tensorflow.contrib.timeseries.python.timeseries.saved_model_utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
from typing import Any as Any, Optional as Optional

def predict_continuation(continue_from: Any, signatures: Any, session: Any, steps: Optional[Any] = ..., times: Optional[Any] = ..., exogenous_features: Optional[Any] = ...): ...
def cold_start_filter(signatures: Any, session: Any, features: Any): ...
def filter_continuation(continue_from: Any, signatures: Any, session: Any, features: Any): ...
