# Stubs for tensorflow.contrib.mixed_precision.python.loss_scale_optimizer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.eager import context as context
from tensorflow.python.ops import control_flow_ops as control_flow_ops, gen_control_flow_ops as gen_control_flow_ops, gen_math_ops as gen_math_ops, math_ops as math_ops
from tensorflow.python.training import optimizer as optimizer
from typing import Any as Any, Optional as Optional

class LossScaleOptimizer(optimizer.Optimizer):
    def __init__(self, opt: Any, loss_scale_manager: Any) -> None: ...
    def compute_gradients(self, loss: Any, var_list: Optional[Any] = ..., gate_gradients: Any = ..., aggregation_method: Optional[Any] = ..., colocate_gradients_with_ops: bool = ..., grad_loss: Optional[Any] = ...): ...
    def apply_gradients(self, grads_and_vars: Any, global_step: Optional[Any] = ..., name: Optional[Any] = ...): ...
