# Stubs for tensorflow.contrib.learn.python.learn.ops.losses_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.framework import deprecated as deprecated
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import math_ops as math_ops, nn as nn
from tensorflow.python.ops.losses import losses as losses
from typing import Any as Any, Optional as Optional

def mean_squared_error_regressor(tensor_in: Any, labels: Any, weights: Any, biases: Any, name: Optional[Any] = ...): ...
def softmax_classifier(tensor_in: Any, labels: Any, weights: Any, biases: Any, class_weight: Optional[Any] = ..., name: Optional[Any] = ...): ...
