# Stubs for tensorflow.contrib.learn.python.learn.ops.seq2seq_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib import rnn as rnn
from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops, nn as nn
from tensorflow.python.util.deprecation import deprecated as deprecated
from typing import Any as Any, Optional as Optional

def sequence_classifier(decoding: Any, labels: Any, sampling_decoding: Optional[Any] = ..., name: Optional[Any] = ...): ...
def seq2seq_inputs(x: Any, y: Any, input_length: Any, output_length: Any, sentinel: Optional[Any] = ..., name: Optional[Any] = ...): ...
def rnn_decoder(decoder_inputs: Any, initial_state: Any, cell: Any, scope: Optional[Any] = ...): ...
def rnn_seq2seq(encoder_inputs: Any, decoder_inputs: Any, encoder_cell: Any, decoder_cell: Optional[Any] = ..., dtype: Any = ..., scope: Optional[Any] = ...): ...
