# Stubs for tensorflow.contrib.ffmpeg.ffmpeg_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.ffmpeg.ops import gen_decode_audio_op_py as gen_decode_audio_op_py, gen_decode_video_op_py as gen_decode_video_op_py, gen_encode_audio_op_py as gen_encode_audio_op_py
from tensorflow.contrib.util import loader as loader
from tensorflow.python.framework import ops as ops
from tensorflow.python.platform import resource_loader as resource_loader
from tensorflow.python.util.deprecation import deprecated as deprecated
from typing import Any as Any, Optional as Optional

def decode_audio(contents: Any, file_format: Optional[Any] = ..., samples_per_second: Optional[Any] = ..., channel_count: Optional[Any] = ..., stream: Optional[Any] = ...): ...
def encode_audio(audio: Any, file_format: Optional[Any] = ..., samples_per_second: Optional[Any] = ...): ...
def decode_video(contents: Any): ...
