# Stubs for tensorflow.contrib.learn.python.learn.trainable (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import abc as abc
from typing import Any as Any, Optional as Optional

class Trainable(metaclass=abc.ABCMeta):
    __metaclass__: Any = ...
    @abc.abstractmethod
    def fit(self, x: Optional[Any] = ..., y: Optional[Any] = ..., input_fn: Optional[Any] = ..., steps: Optional[Any] = ..., batch_size: Optional[Any] = ..., monitors: Optional[Any] = ..., max_steps: Optional[Any] = ...) -> Any: ...
