# Stubs for tensorflow.contrib.timeseries.python.timeseries.state_space_models.test_utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.timeseries.python.timeseries import math_utils as math_utils
from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, linalg_ops as linalg_ops, math_ops as math_ops, random_ops as random_ops
from typing import Any as Any

def transition_power_test_template(test_case: Any, model: Any, num_steps: Any) -> None: ...
def noise_accumulator_test_template(test_case: Any, model: Any, num_steps: Any) -> None: ...
