# Stubs for tensorflow.contrib.signal.python.ops.mel_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.signal.python.ops import shape_ops as shape_ops
from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops
from typing import Any as Any, Optional as Optional

def linear_to_mel_weight_matrix(num_mel_bins: int = ..., num_spectrogram_bins: int = ..., sample_rate: int = ..., lower_edge_hertz: float = ..., upper_edge_hertz: float = ..., dtype: Any = ..., name: Optional[Any] = ...): ...
