# Stubs for tensorflow.contrib.signal.python.ops.mfcc_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops, spectral_ops as spectral_ops
from typing import Any as Any, Optional as Optional

def mfccs_from_log_mel_spectrograms(log_mel_spectrograms: Any, name: Optional[Any] = ...): ...
