# Stubs for tensorflow.contrib.signal.python.ops.reconstruction_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.signal.python.ops import shape_ops as shape_ops, util_ops as util_ops
from tensorflow.python.framework import ops as ops, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops
from typing import Any as Any, Optional as Optional

def overlap_and_add(signal: Any, frame_step: Any, name: Optional[Any] = ...): ...
