# Stubs for tensorflow.contrib.gan.python.losses.python.losses_wargs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.gan.python.losses.python.losses_impl import *
from tensorflow.contrib.gan.python.losses.python import losses_impl as losses_impl
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
