# Stubs for tensorflow.contrib.proto (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.proto.python.ops.decode_proto_op import decode_proto as decode_proto
from tensorflow.contrib.proto.python.ops.encode_proto_op import encode_proto as encode_proto
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
