# Stubs for tensorflow.contrib.rnn.python.tools.checkpoint_convert (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.core.protobuf import saver_pb2 as saver_pb2
from tensorflow.python import pywrap_tensorflow as pywrap_tensorflow
from tensorflow.python.client import session as session
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import variables as variables
from tensorflow.python.platform import app as app
from typing import Any as Any

RNN_NAME_REPLACEMENTS: Any

def convert_names(checkpoint_from_path: Any, checkpoint_to_path: Any, write_v1_checkpoint: bool = ...): ...
def main(_: Any) -> None: ...
