# Stubs for tensorflow.python.estimator.inputs.queues.feeding_queue_runner (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import errors as errors
from tensorflow.python.training import queue_runner as qr
from typing import Any as Any, Optional as Optional

class _FeedingQueueRunner(qr.QueueRunner):
    def __init__(self, queue: Optional[Any] = ..., enqueue_ops: Optional[Any] = ..., close_op: Optional[Any] = ..., cancel_op: Optional[Any] = ..., feed_fns: Optional[Any] = ..., queue_closed_exception_types: Optional[Any] = ...) -> None: ...
    def create_threads(self, sess: Any, coord: Optional[Any] = ..., daemon: bool = ..., start: bool = ...): ...
    def to_proto(self) -> None: ...
