# Stubs for tensorflow.contrib.saved_model.python.saved_model (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.saved_model.python.saved_model import keras_saved_model as keras_saved_model
