# Stubs for tensorflow.contrib.saved_model.python.saved_model.keras_saved_model (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.client import session as session
from tensorflow.python.framework import errors as errors, ops as ops
from tensorflow.python.keras import optimizers as optimizers
from tensorflow.python.keras.models import model_from_json as model_from_json
from tensorflow.python.lib.io import file_io as file_io
from tensorflow.python.ops import variables as variables
from tensorflow.python.platform import gfile as gfile
from tensorflow.python.saved_model import constants as constants
from tensorflow.python.util import compat as compat
from typing import Any as Any, Optional as Optional

def save_keras_model(model: Any, saved_model_path: Any, custom_objects: Optional[Any] = ..., as_text: Optional[Any] = ...): ...
def load_keras_model(saved_model_path: Any): ...
