# Stubs for tensorflow.contrib.text.python.ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.text.python.ops.skip_gram_ops import skip_gram_sample as skip_gram_sample, skip_gram_sample_with_text_vocab as skip_gram_sample_with_text_vocab
