# Stubs for tensorflow.contrib.text.python.ops.gen_skip_gram_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from collections import namedtuple as namedtuple
from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

# _SkipGramGenerateCandidatesOutput = namedtuple('SkipGramGenerateCandidates', <ERROR>)

def skip_gram_generate_candidates(input_tensor: Any, min_skips: Any, max_skips: Any, start: Any, limit: Any, emit_self_as_target: Any, seed: int = ..., seed2: int = ..., name: Optional[Any] = ...): ...
def skip_gram_generate_candidates_eager_fallback(input_tensor: Any, min_skips: Any, max_skips: Any, start: Any, limit: Any, emit_self_as_target: Any, seed: int = ..., seed2: int = ..., name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...
