# Stubs for tensorflow.contrib.text.python.ops.skip_gram_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib import lookup as lookup
from tensorflow.contrib.text.python.ops import gen_skip_gram_ops as gen_skip_gram_ops
from tensorflow.contrib.util import loader as loader
from tensorflow.python.framework import dtypes as dtypes, ops as ops, random_seed as random_seed
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops, random_ops as random_ops
from tensorflow.python.platform import gfile as gfile, resource_loader as resource_loader
from typing import Any as Any, Optional as Optional

def skip_gram_sample(input_tensor: Any, min_skips: int = ..., max_skips: int = ..., start: int = ..., limit: int = ..., emit_self_as_target: bool = ..., vocab_freq_table: Optional[Any] = ..., vocab_min_count: Optional[Any] = ..., vocab_subsampling: Optional[Any] = ..., corpus_size: Optional[Any] = ..., batch_size: Optional[Any] = ..., batch_capacity: Optional[Any] = ..., seed: Optional[Any] = ..., name: Optional[Any] = ...): ...
def skip_gram_sample_with_text_vocab(input_tensor: Any, vocab_freq_file: Any, vocab_token_index: int = ..., vocab_token_dtype: Any = ..., vocab_freq_index: int = ..., vocab_freq_dtype: Any = ..., vocab_delimiter: str = ..., vocab_min_count: int = ..., vocab_subsampling: Optional[Any] = ..., corpus_size: Optional[Any] = ..., min_skips: int = ..., max_skips: int = ..., start: int = ..., limit: int = ..., emit_self_as_target: bool = ..., batch_size: Optional[Any] = ..., batch_capacity: Optional[Any] = ..., seed: Optional[Any] = ..., name: Optional[Any] = ...): ...
