# Stubs for tensorflow.contrib.gan.python.losses.python.tuple_losses_impl (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.gan.python import namedtuples as namedtuples
from tensorflow.contrib.gan.python.losses.python import losses_impl as losses_impl
from tensorflow.python.util import tf_inspect as tf_inspect
from typing import Any as Any, Optional as Optional

wasserstein_generator_loss: Any
wasserstein_discriminator_loss: Any
wasserstein_gradient_penalty: Any
acgan_discriminator_loss: Any
acgan_generator_loss: Any
minimax_discriminator_loss: Any
minimax_generator_loss: Any
modified_discriminator_loss: Any
modified_generator_loss: Any
least_squares_generator_loss: Any
least_squares_discriminator_loss: Any
mutual_information_penalty: Any

def combine_adversarial_loss(gan_loss: Any, gan_model: Any, non_adversarial_loss: Any, weight_factor: Optional[Any] = ..., gradient_ratio: Optional[Any] = ..., gradient_ratio_epsilon: float = ..., scalar_summaries: bool = ..., gradient_summaries: bool = ...): ...
def cycle_consistency_loss(cyclegan_model: Any, scope: Optional[Any] = ..., add_summaries: bool = ...): ...
def stargan_generator_loss_wrapper(loss_fn: Any): ...
def stargan_discriminator_loss_wrapper(loss_fn: Any): ...
def stargan_gradient_penalty_wrapper(loss_fn: Any): ...
