# Stubs for tensorflow.contrib.gan.python.losses.python.tuple_losses (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.gan.python.losses.python.tuple_losses_impl import *
from tensorflow.contrib.gan.python.losses.python import tuple_losses_impl as tuple_losses_impl
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented

# Names in __all__ with no definition:
#   acgan_discriminator_loss
#   acgan_generator_loss
#   combine_adversarial_loss
#   cycle_consistency_loss
#   least_squares_discriminator_loss
#   least_squares_generator_loss
#   minimax_discriminator_loss
#   minimax_generator_loss
#   modified_discriminator_loss
#   modified_generator_loss
#   mutual_information_penalty
#   stargan_discriminator_loss_wrapper
#   stargan_generator_loss_wrapper
#   stargan_gradient_penalty_wrapper
#   wasserstein_discriminator_loss
#   wasserstein_generator_loss
#   wasserstein_gradient_penalty
