# Stubs for tensorflow.contrib.rpc (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.rpc.python.ops.rpc_op import rpc as rpc, try_rpc as try_rpc
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
