# Stubs for tensorflow.contrib.losses.python.metric_learning (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.losses.python.metric_learning.metric_loss_ops import *
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
