# Stubs for tensorflow.contrib.rnn.python.ops.fused_rnn_cell (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import abc as abc
from tensorflow.python.ops import array_ops as array_ops, rnn as rnn
from typing import Any as Any, Optional as Optional

class FusedRNNCell(metaclass=abc.ABCMeta):
    __metaclass__: Any = ...
    @abc.abstractmethod
    def __call__(self, inputs: Any, initial_state: Optional[Any] = ..., dtype: Optional[Any] = ..., sequence_length: Optional[Any] = ..., scope: Optional[Any] = ...) -> Any: ...

class FusedRNNCellAdaptor(FusedRNNCell):
    def __init__(self, cell: Any, use_dynamic_rnn: bool = ...) -> None: ...
    def __call__(self, inputs: Any, initial_state: Optional[Any] = ..., dtype: Optional[Any] = ..., sequence_length: Optional[Any] = ..., scope: Optional[Any] = ...): ...

class TimeReversedFusedRNN(FusedRNNCell):
    def __init__(self, cell: Any) -> None: ...
    def __call__(self, inputs: Any, initial_state: Optional[Any] = ..., dtype: Optional[Any] = ..., sequence_length: Optional[Any] = ..., scope: Optional[Any] = ...): ...
