# Stubs for tensorflow.contrib.layers.python.ops.bucketization_op (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops import math_ops as math_ops
from typing import Any as Any, Optional as Optional

def bucketize(input_tensor: Any, boundaries: Any, name: Optional[Any] = ...): ...
