# Stubs for tensorflow.contrib.libsvm.ops.gen_libsvm_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from collections import namedtuple as namedtuple
from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

# _DecodeLibsvmOutput = namedtuple('DecodeLibsvm', <ERROR>)

def decode_libsvm(input: Any, num_features: Any, dtype: Any = ..., label_dtype: Any = ..., name: Optional[Any] = ...): ...
def decode_libsvm_eager_fallback(input: Any, num_features: Any, dtype: Any = ..., label_dtype: Any = ..., name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...
