# Stubs for tensorflow.contrib.learn.python.learn.ops.embeddings_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.framework import deprecated as deprecated
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import math_ops as math_ops, nn as nn
from typing import Any as Any

def embedding_lookup(params: Any, ids: Any, name: str = ...): ...
def categorical_variable(tensor_in: Any, n_classes: Any, embedding_size: Any, name: Any): ...
