# Stubs for tensorflow.contrib.keras.api.keras.initializers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.initializers import Constant as Constant, Identity as Identity, Initializer as Initializer, Ones as Ones, Orthogonal as Orthogonal, RandomNormal as RandomNormal, RandomUniform as RandomUniform, TruncatedNormal as TruncatedNormal, VarianceScaling as VarianceScaling, Zeros as Zeros, deserialize as deserialize, get as get, glorot_normal as glorot_normal, glorot_uniform as glorot_uniform, he_normal as he_normal, he_uniform as he_uniform, lecun_normal as lecun_normal, lecun_uniform as lecun_uniform, serialize as serialize
