# Stubs for tensorflow.contrib.slim (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.framework.python.ops.arg_scope import *
from tensorflow.contrib.framework.python.ops.variables import *
from tensorflow.contrib.layers.python.layers import *
from tensorflow.contrib.layers.python.layers.initializers import *
from tensorflow.contrib.layers.python.layers.regularizers import *
from tensorflow.contrib import losses as losses, metrics as metrics
from tensorflow.contrib.slim.python.slim import evaluation as evaluation, learning as learning, model_analyzer as model_analyzer, queues as queues, summaries as summaries
from tensorflow.contrib.slim.python.slim.data import data_decoder as data_decoder, data_provider as data_provider, dataset as dataset, dataset_data_provider as dataset_data_provider, parallel_reader as parallel_reader, prefetch_queue as prefetch_queue, tfexample_decoder as tfexample_decoder
from tensorflow.python.util.all_util import make_all as make_all
