# Stubs for tensorflow.contrib.slim.nets (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.slim.python.slim.nets import alexnet as alexnet, inception as inception, overfeat as overfeat, resnet_utils as resnet_utils, resnet_v1 as resnet_v1, resnet_v2 as resnet_v2, vgg as vgg
from tensorflow.python.util.all_util import make_all as make_all
