# Stubs for tensorflow.contrib.optimizer_v2.adadelta (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.optimizer_v2 import optimizer_v2 as optimizer_v2
from tensorflow.python.training import training_ops as training_ops

class AdadeltaOptimizer(optimizer_v2.OptimizerV2):
    def __init__(self, learning_rate: float = ..., rho: float = ..., epsilon: float = ..., use_locking: bool = ..., name: str = ...) -> None: ...
