# Stubs for tensorflow.contrib.optimizer_v2.adagrad (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.optimizer_v2 import optimizer_v2 as optimizer_v2
from tensorflow.python.ops import array_ops as array_ops, gen_array_ops as gen_array_ops, init_ops as init_ops, math_ops as math_ops
from tensorflow.python.training import training_ops as training_ops
from typing import Any as Any

class AdagradOptimizer(optimizer_v2.OptimizerV2):
    def __init__(self, learning_rate: Any, initial_accumulator_value: float = ..., use_locking: bool = ..., name: str = ...) -> None: ...
