# Stubs for tensorflow.python.ops.distributions.bijector (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops.distributions.bijector_impl import Bijector as Bijector
