# Stubs for tensorflow.python.ops.distributions.dirichlet_multinomial (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, control_flow_ops as control_flow_ops, math_ops as math_ops, random_ops as random_ops, special_math_ops as special_math_ops
from tensorflow.python.ops.distributions import distribution as distribution
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

class DirichletMultinomial(distribution.Distribution):
    def __init__(self, total_count: Any, concentration: Any, validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
    @property
    def total_count(self): ...
    @property
    def concentration(self): ...
    @property
    def total_concentration(self): ...
