# Stubs for tensorflow.python.debug.examples.debug_fibonacci (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

FLAGS: Any

def main(_: Any): ...
