# Stubs for tensorflow.python.debug.examples.debug_mnist (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.examples.tutorials.mnist import input_data as input_data
from typing import Any as Any

IMAGE_SIZE: int
HIDDEN_SIZE: int
NUM_LABELS: int
RAND_SEED: int

def main(_: Any): ...
