# Stubs for tensorflow.python.debug.examples.debug_tflearn_iris (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.learn.python.learn.datasets import base as base
from typing import Any as Any

IRIS_TRAINING_DATA_URL: str
IRIS_TEST_DATA_URL: str

def maybe_download_data(data_dir: Any): ...
def iris_input_fn(): ...
def main(_: Any): ...
