# Stubs for tensorflow.contrib.session_bundle.bundle_shim (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.session_bundle import manifest_pb2 as manifest_pb2, session_bundle as session_bundle
from tensorflow.core.protobuf import meta_graph_pb2 as meta_graph_pb2
from tensorflow.python.client import session as session
from tensorflow.python.framework import meta_graph as meta_graph
from tensorflow.python.saved_model import loader as loader, signature_constants as signature_constants
from typing import Any as Any, Optional as Optional

def load_session_bundle_or_saved_model_bundle_from_path(export_dir: Any, tags: Optional[Any] = ..., target: str = ..., config: Optional[Any] = ...): ...
