# Stubs for tensorflow.contrib.distributions.python.ops.bijectors.cholesky_outer_product (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, control_flow_ops as control_flow_ops, linalg_ops as linalg_ops, math_ops as math_ops
from tensorflow.python.ops.distributions import bijector as bijector
from tensorflow.python.util import deprecation as deprecation

class CholeskyOuterProduct(bijector.Bijector):
    def __init__(self, validate_args: bool = ..., name: str = ...) -> None: ...
