# Stubs for tensorflow.contrib.distributions.python.ops.bijectors.inline (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops.distributions import bijector as bijector
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class Inline(bijector.Bijector):
    def __init__(self, forward_fn: Optional[Any] = ..., inverse_fn: Optional[Any] = ..., inverse_log_det_jacobian_fn: Optional[Any] = ..., forward_log_det_jacobian_fn: Optional[Any] = ..., forward_event_shape_fn: Optional[Any] = ..., forward_event_shape_tensor_fn: Optional[Any] = ..., inverse_event_shape_fn: Optional[Any] = ..., inverse_event_shape_tensor_fn: Optional[Any] = ..., is_constant_jacobian: bool = ..., validate_args: bool = ..., forward_min_event_ndims: Optional[Any] = ..., inverse_min_event_ndims: Optional[Any] = ..., name: str = ...) -> None: ...
