# Stubs for tensorflow.contrib.distributions.python.ops.bijectors.invert (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops.distributions import bijector as bijector
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class Invert(bijector.Bijector):
    def __init__(self, bijector: Any, validate_args: bool = ..., name: Optional[Any] = ...) -> None: ...
    @property
    def bijector(self): ...
