# Stubs for tensorflow.contrib.distributions.python.ops.bijectors.masked_autoregressive (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, clip_ops as clip_ops, control_flow_ops as control_flow_ops, init_ops as init_ops, math_ops as math_ops, nn_ops as nn_ops
from tensorflow.python.ops.distributions import bijector as bijector
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class MaskedAutoregressiveFlow(bijector.Bijector):
    def __init__(self, shift_and_log_scale_fn: Any, is_constant_jacobian: bool = ..., validate_args: bool = ..., unroll_loop: bool = ..., name: Optional[Any] = ...) -> None: ...

def masked_dense(inputs: Any, units: Any, num_blocks: Optional[Any] = ..., exclusive: bool = ..., kernel_initializer: Optional[Any] = ..., reuse: Optional[Any] = ..., name: Optional[Any] = ..., *args: Any, **kwargs: Any): ...
def masked_autoregressive_default_template(hidden_layers: Any, shift_only: bool = ..., activation: Any = ..., log_scale_min_clip: Any = ..., log_scale_max_clip: float = ..., log_scale_clip_gradient: bool = ..., name: Optional[Any] = ..., *args: Any, **kwargs: Any): ...
