# Stubs for tensorflow.contrib.distributions.python.ops.bijectors.permute (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import constant_op as constant_op, ops as ops, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, control_flow_ops as control_flow_ops, math_ops as math_ops, nn_ops as nn_ops
from tensorflow.python.ops.distributions import bijector as bijector
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class Permute(bijector.Bijector):
    def __init__(self, permutation: Any, validate_args: bool = ..., name: Optional[Any] = ...) -> None: ...
    @property
    def permutation(self): ...
