# Stubs for tensorflow.contrib.distributions.python.ops.bijectors.scale_tril (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.distributions.python.ops.bijectors import affine_scalar as affine_scalar, chain as chain, fill_triangular as fill_triangular, softplus as softplus, transform_diagonal as transform_diagonal
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class ScaleTriL(chain.Chain):
    def __init__(self, diag_bijector: Optional[Any] = ..., diag_shift: float = ..., validate_args: bool = ..., name: str = ...) -> None: ...
