# Stubs for tensorflow.core.grappler.costs.op_performance_data_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
SessionInfo: Any
OpInfo: Any
NormalDistribution: Any
LogNormalDistribution: Any
OpPerformance: Any
OpPerformanceList: Any
