# Stubs for tensorflow.contrib.decision_trees.proto.generic_tree_model_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
Model: Any
ModelAndFeatures: Any
Ensemble: Any
Summation: Any
Averaging: Any
DecisionTree: Any
TreeNode: Any
BinaryNode: Any
SparseVector: Any
Vector: Any
Leaf: Any
FeatureId: Any
ObliqueFeatures: Any
InequalityTest: Any
Value: Any
