# Stubs for tensorflow.contrib.decision_trees.proto.generic_tree_model_extensions_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
MatchingValuesTest: Any
