# Stubs for tensorflow.python.keras.engine.training_generator (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.eager import context as context
from tensorflow.python.keras.utils.data_utils import GeneratorEnqueuer as GeneratorEnqueuer, OrderedEnqueuer as OrderedEnqueuer, Sequence as Sequence
from tensorflow.python.keras.utils.generic_utils import Progbar as Progbar
from typing import Any as Any, Optional as Optional

def fit_generator(model: Any, generator: Any, steps_per_epoch: Optional[Any] = ..., epochs: int = ..., verbose: int = ..., callbacks: Optional[Any] = ..., validation_data: Optional[Any] = ..., validation_steps: Optional[Any] = ..., class_weight: Optional[Any] = ..., max_queue_size: int = ..., workers: int = ..., use_multiprocessing: bool = ..., shuffle: bool = ..., initial_epoch: int = ...): ...
def evaluate_generator(model: Any, generator: Any, steps: Optional[Any] = ..., max_queue_size: int = ..., workers: int = ..., use_multiprocessing: bool = ..., verbose: int = ...): ...
def predict_generator(model: Any, generator: Any, steps: Optional[Any] = ..., max_queue_size: int = ..., workers: int = ..., use_multiprocessing: bool = ..., verbose: int = ...): ...
