# Stubs for tensorflow.python.keras.engine.training_arrays (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import errors as errors
from tensorflow.python.keras.engine import training_utils as training_utils
from tensorflow.python.keras.utils.generic_utils import Progbar as Progbar, make_batches as make_batches, slice_arrays as slice_arrays
from typing import Any as Any, Optional as Optional

def fit_loop(model: Any, inputs: Any, targets: Any, sample_weights: Optional[Any] = ..., batch_size: Optional[Any] = ..., epochs: int = ..., verbose: int = ..., callbacks: Optional[Any] = ..., val_inputs: Optional[Any] = ..., val_targets: Optional[Any] = ..., val_sample_weights: Optional[Any] = ..., shuffle: bool = ..., initial_epoch: int = ..., steps_per_epoch: Optional[Any] = ..., validation_steps: Optional[Any] = ...): ...
def predict_loop(model: Any, inputs: Any, batch_size: int = ..., verbose: int = ..., steps: Optional[Any] = ...): ...
def test_loop(model: Any, inputs: Any, targets: Any, sample_weights: Optional[Any] = ..., batch_size: Optional[Any] = ..., verbose: int = ..., steps: Optional[Any] = ...): ...
