# Stubs for tensorflow.contrib.image.python.ops.dense_image_warp (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops
from typing import Any as Any

def dense_image_warp(image: Any, flow: Any, name: str = ...): ...
