# Stubs for tensorflow.contrib.framework.python.ops.audio_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops.gen_audio_ops import *
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
