# Stubs for tensorflow.contrib.framework.python.ops.critical_section_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.eager import context as context
from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, gen_resource_variable_ops as gen_resource_variable_ops, tensor_array_ops as tensor_array_ops
from tensorflow.python.util import nest as nest
from typing import Any as Any, Optional as Optional

CRITICAL_SECTIONS: str
CRITICAL_SECTION_EXECUTIONS: str

class _ExecutionSignature: ...

class CriticalSection:
    def __init__(self, name: Optional[Any] = ..., shared_name: Optional[Any] = ..., critical_section_def: Optional[Any] = ..., import_scope: Optional[Any] = ...) -> None: ...
    @property
    def name(self): ...
    def execute(self, fn: Any, *args: Any, **kwargs: Any): ...
