# Stubs for tensorflow.contrib.framework.python.ops.script_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import tensor_shape as tensor_shape
from tensorflow.python.util import nest as nest
from typing import Any as Any, Optional as Optional

def py_func(func: Any, args: Any = ..., kwargs: Optional[Any] = ..., output_types: Optional[Any] = ..., output_shapes: Optional[Any] = ..., stateful: bool = ..., name: Optional[Any] = ...): ...
