# Stubs for tensorflow.contrib.tensor_forest.hybrid.python.layers.fully_connected (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib import layers as layers
from tensorflow.contrib.tensor_forest.hybrid.python import hybrid_layer as hybrid_layer
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops
from typing import Any as Any

class FullyConnectedLayer(hybrid_layer.HybridLayer):
    def inference_graph(self, data: Any): ...

class ManyToOneLayer(hybrid_layer.HybridLayer):
    def inference_graph(self, data: Any): ...

class FlattenedFullyConnectedLayer(hybrid_layer.HybridLayer):
    def inference_graph(self, data: Any): ...
