# Stubs for tensorflow.contrib.kinesis.python.ops.kinesis_op_loader (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.util import loader as loader
from tensorflow.python.platform import resource_loader as resource_loader
