# Stubs for tensorflow.python.ops.distributions.exponential (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops, nn as nn, random_ops as random_ops
from tensorflow.python.ops.distributions import gamma as gamma
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

class Exponential(gamma.Gamma):
    def __init__(self, rate: Any, validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
    @property
    def rate(self): ...

class ExponentialWithSoftplusRate(Exponential):
    def __init__(self, rate: Any, validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
