# Stubs for tensorflow.python.ops.distributions.identity_bijector (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import constant_op as constant_op
from tensorflow.python.ops.distributions import bijector as bijector

class Identity(bijector.Bijector):
    def __init__(self, validate_args: bool = ..., name: str = ...) -> None: ...
