# Stubs for tensorflow.python.ops.distributions.laplace (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops, tensor_shape as tensor_shape
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, math_ops as math_ops, nn as nn, random_ops as random_ops
from tensorflow.python.ops.distributions import distribution as distribution, special_math as special_math
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

class Laplace(distribution.Distribution):
    def __init__(self, loc: Any, scale: Any, validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
    @property
    def loc(self): ...
    @property
    def scale(self): ...

class LaplaceWithSoftplusScale(Laplace):
    def __init__(self, loc: Any, scale: Any, validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
