# Stubs for tensorflow.python.ops.distributions.transformed_distribution (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, control_flow_ops as control_flow_ops, math_ops as math_ops
from tensorflow.python.ops.distributions import distribution as distribution_lib, identity_bijector as identity_bijector
from typing import Any as Any, Optional as Optional

class TransformedDistribution(distribution_lib.Distribution):
    def __init__(self, distribution: Any, bijector: Optional[Any] = ..., batch_shape: Optional[Any] = ..., event_shape: Optional[Any] = ..., validate_args: bool = ..., name: Optional[Any] = ...) -> None: ...
    @property
    def distribution(self): ...
    @property
    def bijector(self): ...
