# Stubs for tensorflow.python.platform.control_imports (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

USE_OSS: bool
OSS_APP: bool
OSS_FLAGS: bool
OSS_GFILE: bool
OSS_GOOGLETEST: bool
OSS_LOGGING: bool
OSS_PARAMETERIZED: bool
