# Stubs for tensorflow.python.platform.self_check (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.platform import build_info as build_info

def preload_check() -> None: ...
