# Stubs for tensorflow.core.profiler.tfprof_output_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
TFProfTensorProto: Any
GraphNodeProto: Any
MultiGraphNodeProto: Any
AdviceProto: Any
