# Stubs for tensorflow.contrib.keras.api.keras.applications.xception (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.applications.xception import Xception as Xception, decode_predictions as decode_predictions, preprocess_input as preprocess_input
