# Stubs for tensorflow.contrib.data (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.data.python.ops.batching import assert_element_shape as assert_element_shape, batch_and_drop_remainder as batch_and_drop_remainder, dense_to_sparse_batch as dense_to_sparse_batch, map_and_batch as map_and_batch, padded_batch_and_drop_remainder as padded_batch_and_drop_remainder, unbatch as unbatch
from tensorflow.contrib.data.python.ops.counter import Counter as Counter
from tensorflow.contrib.data.python.ops.enumerate_ops import enumerate_dataset as enumerate_dataset
from tensorflow.contrib.data.python.ops.error_ops import ignore_errors as ignore_errors
from tensorflow.contrib.data.python.ops.get_single_element import get_single_element as get_single_element, reduce_dataset as reduce_dataset
from tensorflow.contrib.data.python.ops.grouping import Reducer as Reducer, bucket_by_sequence_length as bucket_by_sequence_length, group_by_reducer as group_by_reducer, group_by_window as group_by_window
from tensorflow.contrib.data.python.ops.interleave_ops import choose_from_datasets as choose_from_datasets, parallel_interleave as parallel_interleave, sample_from_datasets as sample_from_datasets, sloppy_interleave as sloppy_interleave
from tensorflow.contrib.data.python.ops.iterator_ops import CheckpointInputPipelineHook as CheckpointInputPipelineHook, make_saveable_from_iterator as make_saveable_from_iterator
from tensorflow.contrib.data.python.ops.parsing_ops import parse_example_dataset as parse_example_dataset
from tensorflow.contrib.data.python.ops.prefetching_ops import copy_to_device as copy_to_device, prefetch_to_device as prefetch_to_device
from tensorflow.contrib.data.python.ops.random_ops import RandomDataset as RandomDataset
from tensorflow.contrib.data.python.ops.readers import CsvDataset as CsvDataset, LMDBDataset as LMDBDataset, SqlDataset as SqlDataset, make_batched_features_dataset as make_batched_features_dataset, make_csv_dataset as make_csv_dataset, read_batch_features as read_batch_features
from tensorflow.contrib.data.python.ops.resampling import rejection_resample as rejection_resample
from tensorflow.contrib.data.python.ops.scan_ops import scan as scan
from tensorflow.contrib.data.python.ops.shuffle_ops import shuffle_and_repeat as shuffle_and_repeat
from tensorflow.contrib.data.python.ops.sliding import sliding_window_batch as sliding_window_batch
from tensorflow.contrib.data.python.ops.unique import unique as unique
from tensorflow.contrib.data.python.ops.writers import TFRecordWriter as TFRecordWriter
from tensorflow.python.data.experimental.ops.optimization import AUTOTUNE as AUTOTUNE
from tensorflow.python.data.ops.iterator_ops import get_next_as_optional as get_next_as_optional
from tensorflow.python.data.ops.optional_ops import Optional as Optional
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
