# Stubs for tensorflow._api.v1.keras.applications.resnet50 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.applications import ResNet50 as ResNet50
from tensorflow.python.keras.applications.resnet50 import decode_predictions as decode_predictions, preprocess_input as preprocess_input
