# Stubs for tensorflow.contrib.nn.python.ops.alpha_dropout (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops, tensor_shape as tensor_shape, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, gen_math_ops as gen_math_ops, math_ops as math_ops, random_ops as random_ops
from typing import Any as Any, Optional as Optional

def alpha_dropout(x: Any, keep_prob: Any, noise_shape: Optional[Any] = ..., seed: Optional[Any] = ..., name: Optional[Any] = ...): ...
