# Stubs for tensorflow.contrib.nn.python.ops.scaled_softplus (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import function as function, ops as ops
from tensorflow.python.ops import array_ops as array_ops, gen_array_ops as gen_array_ops, math_ops as math_ops, nn as nn
from typing import Any as Any, Optional as Optional

def scaled_softplus(x: Any, alpha: Any, clip: Optional[Any] = ..., name: Optional[Any] = ...): ...
