# Stubs for tensorflow.contrib.tpu.python.profiler (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.tpu.profiler.tpu_profiler_analysis_pb2 import *
from tensorflow.contrib.tpu.profiler.trace_events_pb2 import *
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
