# Stubs for tensorflow.contrib.learn.python.learn.estimators (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.learn.python.learn.estimators._sklearn import NotFittedError as NotFittedError
from tensorflow.contrib.learn.python.learn.estimators.constants import ProblemType as ProblemType
from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier as DNNClassifier, DNNEstimator as DNNEstimator, DNNRegressor as DNNRegressor
from tensorflow.contrib.learn.python.learn.estimators.dnn_linear_combined import DNNLinearCombinedClassifier as DNNLinearCombinedClassifier, DNNLinearCombinedEstimator as DNNLinearCombinedEstimator, DNNLinearCombinedRegressor as DNNLinearCombinedRegressor
from tensorflow.contrib.learn.python.learn.estimators.dynamic_rnn_estimator import DynamicRnnEstimator as DynamicRnnEstimator
from tensorflow.contrib.learn.python.learn.estimators.estimator import BaseEstimator as BaseEstimator, Estimator as Estimator, GraphRewriteSpec as GraphRewriteSpec, SKCompat as SKCompat, infer_real_valued_columns_from_input as infer_real_valued_columns_from_input, infer_real_valued_columns_from_input_fn as infer_real_valued_columns_from_input_fn
from tensorflow.contrib.learn.python.learn.estimators.head import Head as Head, binary_svm_head as binary_svm_head, loss_only_head as loss_only_head, multi_class_head as multi_class_head, multi_head as multi_head, multi_label_head as multi_label_head, no_op_train_fn as no_op_train_fn, poisson_regression_head as poisson_regression_head, regression_head as regression_head
from tensorflow.contrib.learn.python.learn.estimators.kmeans import KMeansClustering as KMeansClustering
from tensorflow.contrib.learn.python.learn.estimators.linear import LinearClassifier as LinearClassifier, LinearEstimator as LinearEstimator, LinearRegressor as LinearRegressor
from tensorflow.contrib.learn.python.learn.estimators.logistic_regressor import LogisticRegressor as LogisticRegressor
from tensorflow.contrib.learn.python.learn.estimators.metric_key import MetricKey as MetricKey
from tensorflow.contrib.learn.python.learn.estimators.model_fn import ModeKeys as ModeKeys, ModelFnOps as ModelFnOps
from tensorflow.contrib.learn.python.learn.estimators.prediction_key import PredictionKey as PredictionKey
from tensorflow.contrib.learn.python.learn.estimators.rnn_common import PredictionType as PredictionType
from tensorflow.contrib.learn.python.learn.estimators.run_config import ClusterConfig as ClusterConfig, Environment as Environment, RunConfig as RunConfig, TaskType as TaskType
from tensorflow.contrib.learn.python.learn.estimators.svm import SVM as SVM
