# Stubs for tensorflow.contrib.learn.python.learn.estimators.logistic_regressor (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.learn.python.learn.estimators import constants as constants, estimator as estimator, metric_key as metric_key
from tensorflow.python.ops import math_ops as math_ops
from typing import Any as Any, Optional as Optional

def LogisticRegressor(model_fn: Any, thresholds: Optional[Any] = ..., model_dir: Optional[Any] = ..., config: Optional[Any] = ..., feature_engineering_fn: Optional[Any] = ...): ...
