# Stubs for tensorflow.contrib.learn.python.learn.estimators.model_fn (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.framework import get_graph_from_inputs as get_graph_from_inputs
from tensorflow.contrib.learn.python.learn.estimators import constants as constants, metric_key as metric_key, prediction_key as prediction_key
from tensorflow.python.framework import dtypes as dtypes, ops as ops, sparse_tensor as sparse_tensor, tensor_shape as tensor_shape
from tensorflow.python.ops import array_ops as array_ops
from tensorflow.python.saved_model import signature_constants as signature_constants
from tensorflow.python.training import session_run_hook as session_run_hook
from tensorflow.python.util.deprecation import deprecated as deprecated
from typing import Any as Any, Optional as Optional

class ModeKeys:
    TRAIN: str = ...
    EVAL: str = ...
    INFER: str = ...
    @classmethod
    def validate(cls, key: Any) -> None: ...

class ModelFnOps:
    def __new__(cls, mode: Any, predictions: Optional[Any] = ..., loss: Optional[Any] = ..., train_op: Optional[Any] = ..., eval_metric_ops: Optional[Any] = ..., output_alternatives: Optional[Any] = ..., training_chief_hooks: Optional[Any] = ..., training_hooks: Optional[Any] = ..., scaffold: Optional[Any] = ...): ...
    def estimator_spec(self, default_serving_output_alternative_key: Optional[Any] = ...): ...
