# Stubs for tensorflow.contrib.eager.python.tfe (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.eager.python import metrics as metrics
from tensorflow.contrib.eager.python.datasets import Iterator as Iterator
from tensorflow.contrib.eager.python.network import Network as Network, Sequential as Sequential, restore_network_checkpoint as restore_network_checkpoint, save_network_checkpoint as save_network_checkpoint
from tensorflow.contrib.eager.python.remote import connect_to_remote_host as connect_to_remote_host
from tensorflow.contrib.eager.python.saver import Saver as Saver, get_optimizer_variables as get_optimizer_variables, restore_variables_on_create as restore_variables_on_create
from tensorflow.python.eager import backprop as backprop, function as function
from tensorflow.python.eager.context import ASYNC as ASYNC, DEVICE_PLACEMENT_EXPLICIT as DEVICE_PLACEMENT_EXPLICIT, DEVICE_PLACEMENT_SILENT as DEVICE_PLACEMENT_SILENT, DEVICE_PLACEMENT_WARN as DEVICE_PLACEMENT_WARN, SYNC as SYNC, async_clear_error as async_clear_error, async_wait as async_wait, executing_eagerly as executing_eagerly, execution_mode as execution_mode, list_devices as list_devices, num_gpus as num_gpus, set_execution_mode as set_execution_mode, set_server_def as set_server_def
from tensorflow.python.eager.execution_callbacks import add_execution_callback as add_execution_callback, clear_execution_callbacks as clear_execution_callbacks, inf_callback as inf_callback, inf_nan_callback as inf_nan_callback, nan_callback as nan_callback, seterr as seterr
from tensorflow.python.framework.ops import enable_eager_execution as enable_eager_execution
from tensorflow.python.framework.tensor_spec import TensorSpec as TensorSpec
from tensorflow.python.ops import script_ops as script_ops, template as template
from tensorflow.python.ops.custom_gradient import custom_gradient as custom_gradient
from tensorflow.python.ops.variable_scope import EagerVariableStore as EagerVariableStore
from tensorflow.python.training.checkpointable.tracking import Checkpointable as Checkpointable
from tensorflow.python.training.checkpointable.util import Checkpoint as Checkpoint, CheckpointableSaver as CheckpointableSaver
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented

py_func = script_ops.eager_py_func
defun = function.defun
make_template = template.make_template_internal
implicit_gradients = backprop.implicit_grad
implicit_value_and_gradients = backprop.implicit_val_and_grad
gradients_function = backprop.gradients_function
value_and_gradients_function = backprop.val_and_grad_function
GradientTape = backprop.GradientTape
in_eager_mode = executing_eagerly
