# Stubs for tensorflow.python.data.experimental.ops.enumerate_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.ops import dataset_ops as dataset_ops
from tensorflow.python.framework import dtypes as dtypes
from tensorflow.python.util.tf_export import tf_export as tf_export

def enumerate_dataset(start: int = ...): ...
