# Stubs for tensorflow.python.data.experimental.ops.writers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.ops import dataset_ops as dataset_ops
from tensorflow.python.data.util import convert as convert
from tensorflow.python.framework import dtypes as dtypes, ops as ops, tensor_shape as tensor_shape
from tensorflow.python.ops import gen_dataset_ops as gen_dataset_ops
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

class TFRecordWriter:
    def __init__(self, filename: Any, compression_type: Optional[Any] = ...) -> None: ...
    def write(self, dataset: Any): ...
