# Stubs for tensorflow.keras.estimator (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.estimator import model_to_estimator as model_to_estimator
