# Stubs for tensorflow.contrib.metrics.python.ops.set_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops import sets as sets
from typing import Any as Any

set_size: Any
set_intersection: Any
set_difference: Any
set_union: Any
