# Stubs for tensorflow.contrib.distributions.python.ops.chi2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, math_ops as math_ops
from tensorflow.python.ops.distributions import gamma as gamma
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any

class Chi2(gamma.Gamma):
    def __init__(self, df: Any, validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
    @property
    def df(self): ...

class Chi2WithAbsDf(Chi2):
    def __init__(self, df: Any, validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
