# Stubs for tensorflow.contrib.distributions.python.ops.deterministic (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import abc as abc
from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops, tensor_shape as tensor_shape, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, control_flow_ops as control_flow_ops, math_ops as math_ops
from tensorflow.python.ops.distributions import distribution as distribution
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class _BaseDeterministic(distribution.Distribution, metaclass=abc.ABCMeta):
    def __init__(self, loc: Any, atol: Optional[Any] = ..., rtol: Optional[Any] = ..., is_vector: bool = ..., validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
    @property
    def loc(self): ...
    @property
    def atol(self): ...
    @property
    def rtol(self): ...

class Deterministic(_BaseDeterministic):
    def __init__(self, loc: Any, atol: Optional[Any] = ..., rtol: Optional[Any] = ..., validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...

class VectorDeterministic(_BaseDeterministic):
    def __init__(self, loc: Any, atol: Optional[Any] = ..., rtol: Optional[Any] = ..., validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
