# Stubs for tensorflow.contrib.distributions.python.ops.half_normal (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops, tensor_shape as tensor_shape
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, math_ops as math_ops, nn as nn, random_ops as random_ops
from tensorflow.python.ops.distributions import distribution as distribution, special_math as special_math
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any

class HalfNormal(distribution.Distribution):
    def __init__(self, scale: Any, validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
    @property
    def scale(self): ...
