# Stubs for tensorflow.contrib.distributions.python.ops.kumaraswamy (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.distributions.python.ops import bijectors as bijectors, distribution_util as distribution_util
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, control_flow_ops as control_flow_ops, math_ops as math_ops, special_math_ops as special_math_ops
from tensorflow.python.ops.distributions import distribution as distribution, transformed_distribution as transformed_distribution, uniform as uniform
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class Kumaraswamy(transformed_distribution.TransformedDistribution):
    def __init__(self, concentration1: Optional[Any] = ..., concentration0: Optional[Any] = ..., validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
    @property
    def concentration1(self): ...
    @property
    def concentration0(self): ...
