# Stubs for tensorflow.contrib.distributions.python.ops.moving_stats (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, init_ops as init_ops, math_ops as math_ops, state_ops as state_ops, variable_scope as variable_scope
from typing import Any as Any, Optional as Optional

def assign_moving_mean_variance(mean_var: Any, variance_var: Any, value: Any, decay: Any, name: Optional[Any] = ...): ...
def assign_log_moving_mean_exp(log_mean_exp_var: Any, log_value: Any, decay: Any, name: Optional[Any] = ...): ...
def moving_mean_variance(value: Any, decay: Any, collections: Optional[Any] = ..., name: Optional[Any] = ...): ...
