# Stubs for tensorflow.contrib.distributions.python.ops.mvn_diag (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.distributions.python.ops import distribution_util as distribution_util, mvn_linear_operator as mvn_linop
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import nn as nn
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class MultivariateNormalDiag(mvn_linop.MultivariateNormalLinearOperator):
    def __init__(self, loc: Optional[Any] = ..., scale_diag: Optional[Any] = ..., scale_identity_multiplier: Optional[Any] = ..., validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...

class MultivariateNormalDiagWithSoftplusScale(MultivariateNormalDiag):
    def __init__(self, loc: Any, scale_diag: Any, validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
