# Stubs for tensorflow.contrib.distributions.python.ops.mvn_tril (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.distributions.python.ops import mvn_linear_operator as mvn_linop
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops.linalg import linalg as linalg
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class MultivariateNormalTriL(mvn_linop.MultivariateNormalLinearOperator):
    def __init__(self, loc: Optional[Any] = ..., scale_tril: Optional[Any] = ..., validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
