# Stubs for tensorflow.contrib.distributions.python.ops.mvn_diag_plus_low_rank (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.distributions.python.ops import distribution_util as distribution_util, mvn_linear_operator as mvn_linop
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops.linalg import linalg as linalg
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class MultivariateNormalDiagPlusLowRank(mvn_linop.MultivariateNormalLinearOperator):
    def __init__(self, loc: Optional[Any] = ..., scale_diag: Optional[Any] = ..., scale_identity_multiplier: Optional[Any] = ..., scale_perturb_factor: Optional[Any] = ..., scale_perturb_diag: Optional[Any] = ..., validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
