# Stubs for tensorflow.contrib.distributions.python.ops.normal_conjugate_posteriors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops import math_ops as math_ops
from tensorflow.python.ops.distributions import normal as normal
from typing import Any as Any

def normal_conjugates_known_scale_posterior(prior: Any, scale: Any, s: Any, n: Any): ...
def normal_conjugates_known_scale_predictive(prior: Any, scale: Any, s: Any, n: Any): ...
