# Stubs for tensorflow.contrib.distributions.python.ops.relaxed_bernoulli (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.distributions.python.ops import logistic as logistic
from tensorflow.contrib.distributions.python.ops.bijectors.sigmoid import Sigmoid as Sigmoid
from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops
from tensorflow.python.ops.distributions import transformed_distribution as transformed_distribution
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class RelaxedBernoulli(transformed_distribution.TransformedDistribution):
    def __init__(self, temperature: Any, logits: Optional[Any] = ..., probs: Optional[Any] = ..., validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
    @property
    def temperature(self): ...
    @property
    def logits(self): ...
    @property
    def probs(self): ...
