# Stubs for tensorflow.contrib.distributions.python.ops.vector_student_t (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.distributions.python.ops import bijectors as bijectors, distribution_util as distribution_util
from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops
from tensorflow.python.ops.distributions import student_t as student_t, transformed_distribution as transformed_distribution
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class _VectorStudentT(transformed_distribution.TransformedDistribution):
    def __init__(self, df: Any, loc: Optional[Any] = ..., scale_identity_multiplier: Optional[Any] = ..., scale_diag: Optional[Any] = ..., scale_tril: Optional[Any] = ..., scale_perturb_factor: Optional[Any] = ..., scale_perturb_diag: Optional[Any] = ..., validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
    @property
    def df(self): ...
    @property
    def loc(self): ...
    @property
    def scale(self): ...
