# Stubs for tensorflow.contrib.ffmpeg.ops.gen_decode_video_op_py (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def decode_video(contents: Any, name: Optional[Any] = ...): ...
def decode_video_eager_fallback(contents: Any, name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...
