# Stubs for tensorflow.contrib.deprecated (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops.logging_ops import audio_summary as audio_summary, histogram_summary as histogram_summary, image_summary as image_summary, merge_all_summaries as merge_all_summaries, merge_summary as merge_summary, scalar_summary as scalar_summary
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
