# Stubs for tensorflow.python.estimator.canned.optimizers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.training import adagrad as adagrad, adam as adam, ftrl as ftrl, gradient_descent as gradient_descent, rmsprop as rmsprop
from typing import Any as Any, Optional as Optional

def get_optimizer_instance(opt: Any, learning_rate: Optional[Any] = ...): ...
