# Stubs for tensorflow.contrib.distributions.python.ops.bijectors.affine (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.distributions.python.ops import distribution_util as distribution_util
from tensorflow.contrib.distributions.python.ops.shape import _DistributionShape as _DistributionShape
from tensorflow.python.framework import dtypes as dtypes, ops as ops, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, control_flow_ops as control_flow_ops, math_ops as math_ops
from tensorflow.python.ops.distributions import bijector as bijector
from tensorflow.python.ops.linalg import linalg as linalg
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class Affine(bijector.Bijector):
    def __init__(self, shift: Optional[Any] = ..., scale_identity_multiplier: Optional[Any] = ..., scale_diag: Optional[Any] = ..., scale_tril: Optional[Any] = ..., scale_perturb_factor: Optional[Any] = ..., scale_perturb_diag: Optional[Any] = ..., validate_args: bool = ..., name: str = ...) -> None: ...
    @property
    def shift(self): ...
    @property
    def scale(self): ...
