# Stubs for tensorflow.contrib.distributions.python.ops.bijectors.fill_triangular (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, math_ops as math_ops
from tensorflow.python.ops.distributions import bijector as bijector
from tensorflow.python.util import deprecation as deprecation

class FillTriangular(bijector.Bijector):
    def __init__(self, upper: bool = ..., validate_args: bool = ..., name: str = ...) -> None: ...
