# Stubs for tensorflow.contrib.linear_optimizer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.linear_optimizer.python.ops.sdca_ops import SdcaModel as SdcaModel
from tensorflow.contrib.linear_optimizer.python.ops.sparse_feature_column import SparseFeatureColumn as SparseFeatureColumn
from tensorflow.contrib.linear_optimizer.python.sdca_optimizer import SDCAOptimizer as SDCAOptimizer
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
