# Stubs for tensorflow.contrib.model_pruning (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.model_pruning.python.layers.layers import masked_conv2d as masked_conv2d, masked_convolution as masked_convolution, masked_fully_connected as masked_fully_connected
from tensorflow.contrib.model_pruning.python.layers.rnn_cells import MaskedBasicLSTMCell as MaskedBasicLSTMCell, MaskedLSTMCell as MaskedLSTMCell
from tensorflow.contrib.model_pruning.python.learning import train as train
from tensorflow.contrib.model_pruning.python.pruning import Pruning as Pruning, apply_mask as apply_mask, get_masked_weights as get_masked_weights, get_masks as get_masks, get_pruning_hparams as get_pruning_hparams, get_thresholds as get_thresholds, get_weight_sparsity as get_weight_sparsity, get_weights as get_weights
from tensorflow.contrib.model_pruning.python.strip_pruning_vars_lib import graph_def_from_checkpoint as graph_def_from_checkpoint, strip_pruning_vars_fn as strip_pruning_vars_fn
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
