# Stubs for tensorflow.compat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.compat.compat import forward_compatibility_horizon as forward_compatibility_horizon, forward_compatible as forward_compatible
from tensorflow.python.util.compat import as_bytes as as_bytes, as_str as as_str, as_str_any as as_str_any, bytes_or_text_types as bytes_or_text_types, complex_types as complex_types, integral_types as integral_types, path_to_str as path_to_str, real_types as real_types
