# Stubs for tensorflow.python.pywrap_tensorflow (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.pywrap_tensorflow_internal import *
from tensorflow.python import pywrap_dlopen_global_flags as pywrap_dlopen_global_flags
from tensorflow.python.platform import self_check as self_check
from tensorflow.python.pywrap_tensorflow_internal import __compiler_version__ as __compiler_version__, __cxx11_abi_flag__ as __cxx11_abi_flag__, __git_version__ as __git_version__, __monolithic_build__ as __monolithic_build__, __version__ as __version__
from typing import Any as Any

msg: Any
