# Stubs for tensorflow.python.estimator.inputs.inputs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.estimator.inputs.numpy_io import numpy_input_fn as numpy_input_fn
from tensorflow.python.estimator.inputs.pandas_io import pandas_input_fn as pandas_input_fn
