# Stubs for tensorflow.contrib.distribute.python.input_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.ops import readers as readers
from tensorflow.python.data.util import nest as nest
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops
from tensorflow.python.platform import tf_logging as tf_logging
from typing import Any as Any

def auto_shard_dataset(dataset: Any, num_shards: Any, index: Any): ...
