# Stubs for tensorflow.contrib.distribute.python.monitor (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.eager import context as context
from tensorflow.python.framework import errors as errors
from tensorflow.python.ops import variables as variables
from typing import Any as Any, Optional as Optional

class Monitor:
    def __init__(self, step_callable: Any, session: Optional[Any] = ...) -> None: ...
    def run_steps(self, num_steps: Optional[Any] = ...) -> None: ...
