# Stubs for tensorflow.contrib.slim.python.slim.data.prefetch_queue (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import data_flow_ops as data_flow_ops, math_ops as math_ops
from tensorflow.python.summary import summary as summary
from tensorflow.python.training import queue_runner as queue_runner
from typing import Any as Any, Optional as Optional

def prefetch_queue(tensors: Any, capacity: int = ..., num_threads: int = ..., dynamic_pad: bool = ..., shared_name: Optional[Any] = ..., name: Optional[Any] = ...): ...
