# Stubs for tensorflow.contrib.slim.python.slim.data.test_utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.core.example import example_pb2 as example_pb2, feature_pb2 as feature_pb2
from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes
from tensorflow.python.lib.io import tf_record as tf_record
from tensorflow.python.ops import image_ops as image_ops
from typing import Any as Any

def generate_image(image_shape: Any, image_format: str = ..., label: int = ...): ...
def create_tfrecord_files(output_dir: Any, num_files: int = ..., num_records_per_file: int = ...): ...
