# Stubs for tensorflow.contrib.util.loader (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import load_library as load_library
from tensorflow.python.platform import resource_loader as resource_loader
from typing import Any as Any

def load_op_library(path: Any): ...
