# Stubs for tensorflow.contrib.eager.python.examples.revnet.ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

def downsample(x: Any, filters: Any, strides: Any, axis: int = ...): ...
