# Stubs for tensorflow.contrib.summary.summary (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops.summary_ops_v2 import SummaryWriter as SummaryWriter, all_summary_ops as all_summary_ops, always_record_summaries as always_record_summaries, audio as audio, create_db_writer as create_db_writer, create_file_writer as create_file_writer, create_summary_file_writer as create_summary_file_writer, eval_dir as eval_dir, flush as flush, generic as generic, graph as graph, histogram as histogram, image as image, import_event as import_event, initialize as initialize, never_record_summaries as never_record_summaries, record_summaries_every_n_global_steps as record_summaries_every_n_global_steps, scalar as scalar, should_record_summaries as should_record_summaries, summary_writer_initializer_op as summary_writer_initializer_op
