# Stubs for tensorflow.contrib.quantize.python.input_to_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.quantize.python import common as common
from typing import Any as Any

class InputToOps:
    mapping: Any = ...
    def __init__(self, graph: Any) -> None: ...
    def ConsumerOperations(self, producer_op: Any): ...
