# Stubs for tensorflow.contrib.learn.python.learn.learn_io.generator_io (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.deprecation import deprecated as deprecated
from typing import Any as Any, Optional as Optional

def generator_input_fn(x: Any, target_key: Optional[Any] = ..., batch_size: int = ..., num_epochs: int = ..., shuffle: bool = ..., queue_capacity: int = ..., num_threads: int = ..., pad_value: Optional[Any] = ...): ...
