# Stubs for tensorflow.contrib.lite.toco.toco_flags_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
FileFormat: Any
FILE_FORMAT_UNKNOWN: int
TENSORFLOW_GRAPHDEF: int
TFLITE: int
GRAPHVIZ_DOT: int
TocoFlags: Any
