# Stubs for tensorflow.contrib.lite.toco.types_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
IODataType: Any
IO_DATA_TYPE_UNKNOWN: int
FLOAT: int
QUANTIZED_UINT8: int
INT32: int
INT64: int
STRING: int
QUANTIZED_INT16: int
BOOL: int
