# Stubs for tensorflow.contrib.image.python.ops.interpolate_spline (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, linalg_ops as linalg_ops, math_ops as math_ops
from typing import Any as Any

EPSILON: float

def interpolate_spline(train_points: Any, train_values: Any, query_points: Any, order: Any, regularization_weight: float = ..., name: str = ...): ...
