# Stubs for tensorflow.contrib.image.python.ops.single_image_random_dot_stereograms (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.image.ops import gen_single_image_random_dot_stereograms_ops as gen_single_image_random_dot_stereograms_ops
from tensorflow.contrib.util import loader as loader
from tensorflow.python.framework import ops as ops
from tensorflow.python.platform import resource_loader as resource_loader
from typing import Any as Any, Optional as Optional

def single_image_random_dot_stereograms(depth_values: Any, hidden_surface_removal: Optional[Any] = ..., convergence_dots_size: Optional[Any] = ..., dots_per_inch: Optional[Any] = ..., eye_separation: Optional[Any] = ..., mu: Optional[Any] = ..., normalize: Optional[Any] = ..., normalize_max: Optional[Any] = ..., normalize_min: Optional[Any] = ..., border_level: Optional[Any] = ..., number_colors: Optional[Any] = ..., output_image_shape: Optional[Any] = ..., output_data_window: Optional[Any] = ...): ...
