# Stubs for tensorflow.contrib.image.python.ops.sparse_image_warp (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.image.python.ops import dense_image_warp as dense_image_warp, interpolate_spline as interpolate_spline
from tensorflow.python.framework import constant_op as constant_op, ops as ops
from tensorflow.python.ops import array_ops as array_ops
from typing import Any as Any

def sparse_image_warp(image: Any, source_control_point_locations: Any, dest_control_point_locations: Any, interpolation_order: int = ..., regularization_weight: float = ..., num_boundary_points: int = ..., name: str = ...): ...
