# Stubs for tensorflow.python.estimator.api (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from __future__ import print_function as print_function
from tensorflow.python.estimator.api import estimator as estimator
