# Stubs for tensorflow.keras.losses (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.losses import KLD as KLD, MAE as MAE, MAPE as MAPE, MSE as MSE, MSLE as MSLE, binary_crossentropy as binary_crossentropy, categorical_crossentropy as categorical_crossentropy, categorical_hinge as categorical_hinge, cosine as cosine, deserialize as deserialize, get as get, hinge as hinge, logcosh as logcosh, poisson as poisson, serialize as serialize, sparse_categorical_crossentropy as sparse_categorical_crossentropy, squared_hinge as squared_hinge
