# Stubs for tensorflow.contrib.bayesflow.python.ops.monte_carlo_impl (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops, nn as nn
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

def expectation_importance_sampler(f: Any, log_p: Any, sampling_dist_q: Any, z: Optional[Any] = ..., n: Optional[Any] = ..., seed: Optional[Any] = ..., name: str = ...): ...
def expectation_importance_sampler_logspace(log_f: Any, log_p: Any, sampling_dist_q: Any, z: Optional[Any] = ..., n: Optional[Any] = ..., seed: Optional[Any] = ..., name: str = ...): ...
def expectation(f: Any, samples: Any, log_prob: Optional[Any] = ..., use_reparametrization: bool = ..., axis: int = ..., keep_dims: bool = ..., name: Optional[Any] = ...): ...
