# Stubs for tensorflow.contrib.keras.api.keras.applications (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.keras.api.keras.applications import inception_v3 as inception_v3, mobilenet as mobilenet, resnet50 as resnet50, vgg16 as vgg16, vgg19 as vgg19, xception as xception
from tensorflow.contrib.keras.api.keras.applications.inception_v3 import InceptionV3 as InceptionV3
from tensorflow.contrib.keras.api.keras.applications.mobilenet import MobileNet as MobileNet
from tensorflow.contrib.keras.api.keras.applications.resnet50 import ResNet50 as ResNet50
from tensorflow.contrib.keras.api.keras.applications.vgg16 import VGG16 as VGG16
from tensorflow.contrib.keras.api.keras.applications.vgg19 import VGG19 as VGG19
from tensorflow.contrib.keras.api.keras.applications.xception import Xception as Xception
