# Stubs for tensorflow.contrib.tensor_forest.proto.tensor_forest_params_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
LeafModelType: Any
StatsModelType: Any
SplitCollectionType: Any
SplitPruningStrategyType: Any
SplitFinishStrategyType: Any
MODEL_DENSE_CLASSIFICATION: int
MODEL_SPARSE_CLASSIFICATION: int
MODEL_REGRESSION: int
MODEL_SPARSE_OR_DENSE_CLASSIFICATION: int
STATS_DENSE_GINI: int
STATS_SPARSE_GINI: int
STATS_LEAST_SQUARES_REGRESSION: int
STATS_SPARSE_THEN_DENSE_GINI: int
STATS_FIXED_SIZE_SPARSE_GINI: int
COLLECTION_BASIC: int
GRAPH_RUNNER_COLLECTION: int
SPLIT_PRUNE_NONE: int
SPLIT_PRUNE_HALF: int
SPLIT_PRUNE_QUARTER: int
SPLIT_PRUNE_10_PERCENT: int
SPLIT_PRUNE_HOEFFDING: int
SPLIT_FINISH_BASIC: int
SPLIT_FINISH_DOMINATE_HOEFFDING: int
SPLIT_FINISH_DOMINATE_BOOTSTRAP: int
SplitPruningConfig: Any
SplitFinishConfig: Any
LinearParam: Any
ExponentialParam: Any
ThresholdParam: Any
DepthDependentParam: Any
TensorForestParams: Any
