# Stubs for tensorflow.contrib.fused_conv.ops.gen_fused_conv2d_bias_activation_op (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def fused_conv2d_bias_activation(conv_input: Any, filter: Any, bias: Any, side_input: Any, conv_input_scale: Any, side_input_scale: Any, strides: Any, padding: Any, data_format: str = ..., filter_format: str = ..., activation_mode: str = ..., dilations: Any = ..., name: Optional[Any] = ...): ...
def fused_conv2d_bias_activation_eager_fallback(conv_input: Any, filter: Any, bias: Any, side_input: Any, conv_input_scale: Any, side_input_scale: Any, strides: Any, padding: Any, data_format: str = ..., filter_format: str = ..., activation_mode: str = ..., dilations: Any = ..., name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...
