# Stubs for tensorflow.python.eager.core (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python import pywrap_tensorflow as pywrap_tensorflow
from tensorflow.python.framework import errors as errors
from typing import Any as Any

class _NotOkStatusException(Exception):
    message: Any = ...
    code: Any = ...
    def __init__(self, message: Any, code: Any) -> None: ...

class _FallbackException(Exception): ...
