# Stubs for tensorflow.python.eager.def_function (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.eager import context as context, function as function
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import control_flow_ops as control_flow_ops, resource_variable_ops as resource_variable_ops, variable_scope as variable_scope
from typing import Any as Any, Optional as Optional

class UnliftedInitializerVariable(resource_variable_ops.ResourceVariable):
    def __init__(self, initial_value: Optional[Any] = ..., trainable: bool = ..., caching_device: Optional[Any] = ..., name: Optional[Any] = ..., dtype: Optional[Any] = ..., constraint: Optional[Any] = ..., **unused_kwargs: Any) -> None: ...

def def_function(fn: Any): ...
