# Stubs for tensorflow.python.eager.graph_only_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.core.framework import attr_value_pb2 as attr_value_pb2
from tensorflow.python.framework import ops as ops, tensor_shape as tensor_shape
from typing import Any as Any, Optional as Optional

def graph_zeros_like(tensor: Any): ...
def graph_placeholder(dtype: Any, shape: Any, name: Optional[Any] = ...): ...
