# Stubs for tensorflow.contrib.cluster_resolver.python.training (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.cluster_resolver.python.training.cluster_resolver import ClusterResolver as ClusterResolver, SimpleClusterResolver as SimpleClusterResolver, UnionClusterResolver as UnionClusterResolver
from tensorflow.contrib.cluster_resolver.python.training.gce_cluster_resolver import GceClusterResolver as GceClusterResolver
from tensorflow.contrib.cluster_resolver.python.training.tpu_cluster_resolver import TPUClusterResolver as TPUClusterResolver
