# Stubs for tensorflow.contrib.cloud.python.ops.gen_bigquery_reader_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def big_query_reader(project_id: Any, dataset_id: Any, table_id: Any, columns: Any, timestamp_millis: Any, container: str = ..., shared_name: str = ..., test_end_point: str = ..., name: Optional[Any] = ...): ...
def generate_big_query_reader_partitions(project_id: Any, dataset_id: Any, table_id: Any, columns: Any, timestamp_millis: Any, num_partitions: Any, test_end_point: str = ..., name: Optional[Any] = ...): ...
def generate_big_query_reader_partitions_eager_fallback(project_id: Any, dataset_id: Any, table_id: Any, columns: Any, timestamp_millis: Any, num_partitions: Any, test_end_point: str = ..., name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...
