# Stubs for tensorflow.contrib (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib import autograph as autograph, batching as batching, bayesflow as bayesflow, checkpoint as checkpoint, cloud as cloud, cluster_resolver as cluster_resolver, coder as coder, compiler as compiler, constrained_optimization as constrained_optimization, copy_graph as copy_graph, crf as crf, cudnn_rnn as cudnn_rnn, data as data, deprecated as deprecated, distribute as distribute, distributions as distributions, estimator as estimator, factorization as factorization, feature_column as feature_column, framework as framework, gan as gan, graph_editor as graph_editor, grid_rnn as grid_rnn, image as image, input_pipeline as input_pipeline, integrate as integrate, keras as keras, kernel_methods as kernel_methods, labeled_tensor as labeled_tensor, layers as layers, learn as learn, legacy_seq2seq as legacy_seq2seq, linear_optimizer as linear_optimizer, lookup as lookup, losses as losses, memory_stats as memory_stats, metrics as metrics, mixed_precision as mixed_precision, model_pruning as model_pruning, nccl as nccl, nn as nn, opt as opt, periodic_resample as periodic_resample, predictor as predictor, proto as proto, quantization as quantization, quantize as quantize, reduce_slice_ops as reduce_slice_ops, resampler as resampler, rnn as rnn, rpc as rpc, saved_model as saved_model, seq2seq as seq2seq, signal as signal, slim as slim, solvers as solvers, sparsemax as sparsemax, staging as staging, stat_summarizer as stat_summarizer, stateless as stateless, tensor_forest as tensor_forest, tensorboard as tensorboard, testing as testing, tfprof as tfprof, timeseries as timeseries, tpu as tpu, training as training, util as util
from tensorflow.contrib.lite.python import lite as lite
from tensorflow.contrib.summary import summary as summary
from tensorflow.python.tools import component_api_helper as component_api_helper
from tensorflow.python.util.lazy_loader import LazyLoader as LazyLoader
from typing import Any as Any

ffmpeg: Any
