# Stubs for tensorflow.contrib.data.python.ops.counter (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.experimental.ops import counter as counter
from tensorflow.python.framework import dtypes as dtypes
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any

def Counter(start: int = ..., step: int = ..., dtype: Any = ...): ...
