# Stubs for tensorflow.contrib.data.python.ops.enumerate_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.experimental.ops import enumerate_ops as enumerate_ops
from tensorflow.python.util import deprecation as deprecation

def enumerate_dataset(start: int = ...): ...
