# Stubs for tensorflow.contrib.data.python.ops.error_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.experimental.ops import error_ops as error_ops
from tensorflow.python.util import deprecation as deprecation

def ignore_errors(): ...
