# Stubs for tensorflow.contrib.data.python.ops.random_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.experimental.ops import random_ops as random_ops
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class RandomDataset(random_ops.RandomDataset):
    def __init__(self, seed: Optional[Any] = ...) -> None: ...
