# Stubs for tensorflow.contrib.data.python.ops.shuffle_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.experimental.ops import shuffle_ops as shuffle_ops
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

def shuffle_and_repeat(buffer_size: Any, count: Optional[Any] = ..., seed: Optional[Any] = ...): ...
