# Stubs for tensorflow.contrib.data.python.ops.sliding (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.ops import dataset_ops as dataset_ops
from tensorflow.python.data.util import nest as nest
from tensorflow.python.framework import dtypes as dtypes, ops as ops, tensor_shape as tensor_shape
from tensorflow.python.ops import gen_dataset_ops as gen_dataset_ops
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class _SlideDataset(dataset_ops.UnaryDataset):
    def __init__(self, input_dataset: Any, window_size: Any, window_shift: Any, window_stride: Any) -> None: ...
    @property
    def output_classes(self): ...
    @property
    def output_shapes(self): ...
    @property
    def output_types(self): ...

def sliding_window_batch(window_size: Any, stride: Optional[Any] = ..., window_shift: Optional[Any] = ..., window_stride: int = ...): ...
