# Stubs for tensorflow.contrib.solvers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.solvers.python.ops import lanczos as lanczos, least_squares as least_squares, linear_equations as linear_equations, util as util
