# Stubs for tensorflow.train.queue_runner (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.training.queue_runner import QueueRunner as QueueRunner, add_queue_runner as add_queue_runner, start_queue_runners as start_queue_runners
