# Stubs for tensorflow.contrib.integrate.python.ops.odes (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import abc as abc
from collections import namedtuple as namedtuple
from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, math_ops as math_ops, tensor_array_ops as tensor_array_ops
from typing import Any as Any, Optional as Optional

_ButcherTableau = namedtuple('_ButcherTableau', 'alpha beta c_sol c_mid c_error')

class _RungeKuttaState: ...
class _History: ...

def odeint(func: Any, y0: Any, t: Any, rtol: float = ..., atol: float = ..., method: Optional[Any] = ..., options: Optional[Any] = ..., full_output: bool = ..., name: Optional[Any] = ...): ...

class _FixedGridIntegrator(metaclass=abc.ABCMeta):
    def integrate(self, evol_func: Any, y0: Any, time_grid: Any, dt_grid: Any, steps_on_intervals: Any): ...

class _MidpointFixedGridIntegrator(_FixedGridIntegrator): ...
class _RK4FixedGridIntegrator(_FixedGridIntegrator): ...

def odeint_fixed(func: Any, y0: Any, t: Any, dt: Optional[Any] = ..., method: str = ..., name: Optional[Any] = ...): ...
