# Stubs for tensorflow.contrib.cmake.tools.create_def_file (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

UNDNAME: str
DUMPBIN: str
EXCLUDE_RE: Any
INCLUDEPRE_RE: Any
INCLUDE_RE: Any
DATA_EXCLUDE_RE: Any

def get_args(): ...
def main(): ...
