# Stubs for tensorflow.contrib.optimizer_v2.adam (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.optimizer_v2 import optimizer_v2 as optimizer_v2
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import control_flow_ops as control_flow_ops, math_ops as math_ops, resource_variable_ops as resource_variable_ops, state_ops as state_ops
from tensorflow.python.training import training_ops as training_ops

class AdamOptimizer(optimizer_v2.OptimizerV2):
    def __init__(self, learning_rate: float = ..., beta1: float = ..., beta2: float = ..., epsilon: float = ..., use_locking: bool = ..., name: str = ...) -> None: ...
