# Stubs for tensorflow.python.saved_model.loader (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.saved_model.loader_impl import load as load, maybe_saved_model_directory as maybe_saved_model_directory
