# Stubs for tensorflow.python.saved_model.main_op (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.saved_model.main_op_impl import main_op as main_op, main_op_with_restore as main_op_with_restore
