# Stubs for tensorflow.python.saved_model.tag_constants (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.tf_export import tf_export as tf_export

SERVING: str
TRAINING: str
EVAL: str
GPU: str
TPU: str
