# Stubs for tensorflow.python.distribute.distribute_config (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any, Optional as Optional

class DistributeConfig:
    def __new__(cls, train_distribute: Optional[Any] = ..., eval_distribute: Optional[Any] = ..., remote_cluster: Optional[Any] = ...): ...
