# Stubs for tensorflow.python.distribute.multi_worker_util (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.core.protobuf import cluster_pb2 as cluster_pb2
from tensorflow.python.training import server_lib as server_lib
from typing import Any as Any

def normalize_cluster_spec(cluster_spec: Any): ...
def is_chief(cluster_spec: Any, task_type: Any, task_id: Any): ...
