# Stubs for tensorflow.python.estimator.estimator_lib (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.estimator.canned.baseline import BaselineClassifier as BaselineClassifier, BaselineRegressor as BaselineRegressor
from tensorflow.python.estimator.canned.boosted_trees import BoostedTreesClassifier as BoostedTreesClassifier, BoostedTreesRegressor as BoostedTreesRegressor
from tensorflow.python.estimator.canned.dnn import DNNClassifier as DNNClassifier, DNNRegressor as DNNRegressor
from tensorflow.python.estimator.canned.dnn_linear_combined import DNNLinearCombinedClassifier as DNNLinearCombinedClassifier, DNNLinearCombinedRegressor as DNNLinearCombinedRegressor
from tensorflow.python.estimator.canned.linear import LinearClassifier as LinearClassifier, LinearRegressor as LinearRegressor
from tensorflow.python.estimator.canned.parsing_utils import classifier_parse_example_spec as classifier_parse_example_spec, regressor_parse_example_spec as regressor_parse_example_spec
from tensorflow.python.estimator.estimator import Estimator as Estimator, VocabInfo as VocabInfo, WarmStartSettings as WarmStartSettings
from tensorflow.python.estimator.exporter import Exporter as Exporter, FinalExporter as FinalExporter, LatestExporter as LatestExporter
from tensorflow.python.estimator.inputs import inputs as inputs
from tensorflow.python.estimator.keras import model_to_estimator as model_to_estimator
from tensorflow.python.estimator.model_fn import EstimatorSpec as EstimatorSpec, ModeKeys as ModeKeys
from tensorflow.python.estimator.run_config import RunConfig as RunConfig
from tensorflow.python.estimator.training import EvalSpec as EvalSpec, TrainSpec as TrainSpec, train_and_evaluate as train_and_evaluate
