# Stubs for tensorflow.python.estimator.keras (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.client import session as session
from tensorflow.python.framework import ops as ops, random_seed as random_seed, tensor_util as tensor_util
from tensorflow.python.keras import metrics as metrics, models as models, optimizers as optimizers
from tensorflow.python.ops import check_ops as check_ops, math_ops as math_ops
from tensorflow.python.platform import gfile as gfile
from tensorflow.python.saved_model import signature_constants as signature_constants
from tensorflow.python.training import checkpoint_management as checkpoint_management, distribution_strategy_context as distribution_strategy_context, training_util as training_util
from typing import Any as Any, Optional as Optional

def model_to_estimator(keras_model: Optional[Any] = ..., keras_model_path: Optional[Any] = ..., custom_objects: Optional[Any] = ..., model_dir: Optional[Any] = ..., config: Optional[Any] = ...): ...
