# Stubs for tensorflow.contrib.training.python.training.sampling_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, control_flow_ops as control_flow_ops, logging_ops as logging_ops, math_ops as math_ops, random_ops as random_ops, variable_scope as variable_scope
from typing import Any as Any, Optional as Optional

def rejection_sample(tensors: Any, accept_prob_fn: Any, batch_size: Any, queue_threads: int = ..., enqueue_many: bool = ..., prebatch_capacity: int = ..., prebatch_threads: int = ..., runtime_checks: bool = ..., name: Optional[Any] = ...): ...
def stratified_sample(tensors: Any, labels: Any, target_probs: Any, batch_size: Any, init_probs: Optional[Any] = ..., enqueue_many: bool = ..., queue_capacity: int = ..., threads_per_queue: int = ..., name: Optional[Any] = ...): ...
