# Stubs for tensorflow.contrib.fused_conv.python.ops.fused_conv2d_bias_activation_op (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.fused_conv.ops import gen_fused_conv2d_bias_activation_op as gen_fused_conv2d_bias_activation_op
from tensorflow.contrib.util import loader as loader
from tensorflow.python.platform import resource_loader as resource_loader
from typing import Any as Any, Optional as Optional

def fused_conv2d_bias_activation(conv_input: Any, filter: Any, bias: Any, strides: Optional[Any] = ..., padding: Optional[Any] = ..., conv_input_scale: float = ..., side_input_scale: float = ..., side_input: Optional[Any] = ..., activation_mode: str = ..., data_format: Optional[Any] = ..., filter_format: Optional[Any] = ..., name: Optional[Any] = ...): ...
