# Stubs for tensorflow.python.client.device_lib (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.core.framework import device_attributes_pb2 as device_attributes_pb2
from tensorflow.python import pywrap_tensorflow as pywrap_tensorflow
from typing import Any as Any, Optional as Optional

def list_local_devices(session_config: Optional[Any] = ...): ...
