# Stubs for tensorflow.contrib.meta_graph_transform (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.meta_graph_transform import meta_graph_transform as meta_graph_transform
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
