# Stubs for tensorflow.contrib.keras.api.keras.preprocessing.image (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.preprocessing.image import DirectoryIterator as DirectoryIterator, ImageDataGenerator as ImageDataGenerator, Iterator as Iterator, NumpyArrayIterator as NumpyArrayIterator, array_to_img as array_to_img, img_to_array as img_to_array, load_img as load_img, random_channel_shift as random_channel_shift, random_rotation as random_rotation, random_shear as random_shear, random_shift as random_shift, random_zoom as random_zoom
