# Stubs for tensorflow.contrib.receptive_field.receptive_field_api (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.receptive_field.python.util.graph_compute_order import get_compute_order as get_compute_order
from tensorflow.contrib.receptive_field.python.util.receptive_field import compute_receptive_field_from_graph_def as compute_receptive_field_from_graph_def
