# Stubs for tensorflow.contrib.eager.python.remote (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.core.protobuf.cluster_pb2 import ClusterDef as ClusterDef
from tensorflow.core.protobuf.tensorflow_server_pb2 import ServerDef as ServerDef
from tensorflow.python.eager import context as context
from typing import Any as Any, Optional as Optional

def connect_to_remote_host(remote_host: Optional[Any] = ..., job_name: str = ...) -> None: ...
