# Stubs for tensorflow.contrib.factorization.python.ops.gen_factorization_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from collections import namedtuple as namedtuple
from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def masked_matmul(a: Any, b: Any, mask_indices: Any, transpose_a: Any, transpose_b: Any, name: Optional[Any] = ...): ...
def masked_matmul_eager_fallback(a: Any, b: Any, mask_indices: Any, transpose_a: Any, transpose_b: Any, name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...

# _WALSComputePartialLhsAndRhsOutput = namedtuple('WALSComputePartialLhsAndRhs', <ERROR>)

def wals_compute_partial_lhs_and_rhs(factors: Any, factor_weights: Any, unobserved_weights: Any, input_weights: Any, input_indices: Any, input_values: Any, entry_weights: Any, input_block_size: Any, input_is_transpose: Any, name: Optional[Any] = ...): ...
def wals_compute_partial_lhs_and_rhs_eager_fallback(factors: Any, factor_weights: Any, unobserved_weights: Any, input_weights: Any, input_indices: Any, input_values: Any, entry_weights: Any, input_block_size: Any, input_is_transpose: Any, name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...
