# Stubs for tensorflow.python.autograph.lang.directives (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

UNSPECIFIED: Any

def set_element_type(entity: Any, dtype: Any, shape: Any = ...) -> None: ...
def set_loop_options(parallel_iterations: Any = ..., back_prop: Any = ..., swap_memory: Any = ..., maximum_iterations: Any = ...) -> None: ...
