# Stubs for tensorflow.python.autograph.lang.special_functions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.autograph.operators import data_structures as data_structures
from typing import Any as Any, Optional as Optional

def tensor_list(elements: Any, element_dtype: Optional[Any] = ..., element_shape: Optional[Any] = ..., use_tensor_array: bool = ...): ...
def stack(list_or_tensor: Any, element_dtype: Optional[Any] = ..., strict: bool = ...): ...
