# Stubs for tensorflow.contrib.training (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.training.python.training.bucket_ops import *
from tensorflow.contrib.training.python.training.device_setter import *
from tensorflow.contrib.training.python.training.hparam import *
from tensorflow.contrib.training.python.training.resample import *
from tensorflow.contrib.training.python.training.sampling_ops import *
from tensorflow.contrib.training.python.training.sequence_queueing_state_saver import *
from tensorflow.contrib.training.python.training.evaluation import StopAfterNEvalsHook as StopAfterNEvalsHook, SummaryAtEndHook as SummaryAtEndHook, checkpoints_iterator as checkpoints_iterator, evaluate_once as evaluate_once, evaluate_repeatedly as evaluate_repeatedly, get_or_create_eval_step as get_or_create_eval_step, wait_for_new_checkpoint as wait_for_new_checkpoint
from tensorflow.contrib.training.python.training.feeding_queue_runner import FeedingQueueRunner as FeedingQueueRunner
from tensorflow.contrib.training.python.training.tensor_queue_dataset import enqueue_in_queue_dataset as enqueue_in_queue_dataset, prepend_from_queue_and_padded_batch_dataset as prepend_from_queue_and_padded_batch_dataset
from tensorflow.contrib.training.python.training.training import add_gradients_summaries as add_gradients_summaries, clip_gradient_norms as clip_gradient_norms, clip_gradient_norms_fn as clip_gradient_norms_fn, create_train_op as create_train_op, multiply_gradients as multiply_gradients, train as train
from tensorflow.contrib.training.python.training.tuner import Tuner as Tuner
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
