# Stubs for tensorflow.contrib.training.python.training.resample (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, math_ops as math_ops, random_ops as random_ops, tensor_array_ops as tensor_array_ops, variable_scope as variable_scope
from tensorflow.python.training import moving_averages as moving_averages
from typing import Any as Any, Optional as Optional

def resample_at_rate(inputs: Any, rates: Any, scope: Optional[Any] = ..., seed: Optional[Any] = ..., back_prop: bool = ...): ...
def weighted_resample(inputs: Any, weights: Any, overall_rate: Any, scope: Optional[Any] = ..., mean_decay: float = ..., seed: Optional[Any] = ...): ...
