# Stubs for tensorflow.contrib.training.python.training.tuner (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import abc as abc
from tensorflow.contrib.framework.python.framework import experimental as experimental
from typing import Any as Any

class Tuner(metaclass=abc.ABCMeta):
    __metaclass__: Any = ...
    @abc.abstractmethod
    def next_trial(self) -> Any: ...
    @abc.abstractmethod
    def run_experiment(self, experiment_fn: Any) -> Any: ...
