# Stubs for tensorflow.contrib.learn.python.learn.utils.inspect_checkpoint (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.framework.python.framework import checkpoint_utils as checkpoint_utils
from tensorflow.python.platform import app as app
from typing import Any as Any

FLAGS: Any

def print_tensors_in_checkpoint_file(file_name: Any, tensor_name: Any) -> None: ...
def main(unused_argv: Any) -> None: ...
