# Stubs for tensorflow.contrib.learn.python.learn.summary_writer_cache (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.training import summary_io as summary_io
from typing import Any as Any

SummaryWriterCache = summary_io.SummaryWriterCache
clear_summary_writers: Any
get_summary_writer: Any
