# Stubs for tensorflow.python.profiler.internal.flops_registry (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import graph_util as graph_util, ops as ops
from typing import Any as Any

IMPLEMENTED_OPS: Any
