# Stubs for tensorflow.contrib.recurrent.python.recurrent_api (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.recurrent.python.ops.functional_rnn import bidirectional_functional_rnn as bidirectional_functional_rnn, functional_rnn as functional_rnn
from tensorflow.contrib.recurrent.python.ops.recurrent import Recurrent as Recurrent
