# Stubs for tensorflow._api.v1.keras.initializers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python import Constant as Constant, Identity as Identity, Initializer as Initializer, Ones as Ones, Orthogonal as Orthogonal, VarianceScaling as VarianceScaling, Zeros as Zeros, he_normal as he_normal, he_uniform as he_uniform, lecun_normal as lecun_normal, lecun_uniform as lecun_uniform
from tensorflow.python.keras.initializers import RandomNormal as RandomNormal, RandomUniform as RandomUniform, TruncatedNormal as TruncatedNormal, deserialize as deserialize, get as get, serialize as serialize
