# Stubs for tensorflow.contrib.receptive_field.python.util.parse_layer_parameters (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.util import make_ndarray as make_ndarray
from typing import Any as Any, Optional as Optional

def get_layer_params(node: Any, name_to_node: Any, input_resolution: Optional[Any] = ..., force: bool = ...): ...
