# Stubs for tensorflow.contrib.keras.api.keras.constraints (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.constraints import Constraint as Constraint, MaxNorm as MaxNorm, MinMaxNorm as MinMaxNorm, NonNeg as NonNeg, UnitNorm as UnitNorm, deserialize as deserialize, get as get, max_norm as max_norm, min_max_norm as min_max_norm, non_neg as non_neg, serialize as serialize, unit_norm as unit_norm
