# Stubs for tensorflow.python.keras.models (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras import optimizers as optimizers
from tensorflow.python.keras.engine import saving as saving, sequential as sequential, training as training
from tensorflow.python.keras.engine.base_layer import Layer as Layer
from tensorflow.python.keras.engine.input_layer import Input as Input, InputLayer as InputLayer
from tensorflow.python.keras.engine.network import Network as Network
from tensorflow.python.keras.utils import generic_utils as generic_utils
from tensorflow.python.keras.utils.generic_utils import CustomObjectScope as CustomObjectScope
from tensorflow.python.training.checkpointable import data_structures as data_structures
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

Model = training.Model
Sequential = sequential.Sequential
save_model = saving.save_model
load_model = saving.load_model
model_from_config = saving.model_from_config
model_from_yaml = saving.model_from_yaml
model_from_json = saving.model_from_json

def clone_model(model: Any, input_tensors: Optional[Any] = ...): ...
def in_place_subclassed_model_state_restoration(model: Any) -> None: ...
def clone_and_build_model(model: Any, input_tensors: Optional[Any] = ..., target_tensors: Optional[Any] = ..., custom_objects: Optional[Any] = ..., compile_clone: bool = ..., in_place_reset: bool = ..., optimizer_iterations: Optional[Any] = ...): ...
