# Stubs for tensorflow.contrib.seq2seq.python.ops.loss (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops, nn_ops as nn_ops
from typing import Any as Any, Optional as Optional

def sequence_loss(logits: Any, targets: Any, weights: Any, average_across_timesteps: bool = ..., average_across_batch: bool = ..., softmax_loss_function: Optional[Any] = ..., name: Optional[Any] = ...): ...
