# Stubs for tensorflow.contrib.remote_fused_graph.pylib.python.ops.remote_fused_graph_ops_test (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.remote_fused_graph.pylib.python.ops import remote_fused_graph_ops as remote_fused_graph_ops
from tensorflow.core.framework import graph_pb2 as graph_pb2
from tensorflow.python.framework import dtypes as dtypes, ops as ops, test_util as test_util
from tensorflow.python.platform import googletest as googletest

class RemoteFusedGraphExecuteTest(test_util.TensorFlowTestCase):
    def testBuild(self) -> None: ...
