# Stubs for tensorflow.python.keras.utils.np_utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def to_categorical(y: Any, num_classes: Optional[Any] = ...): ...
def normalize(x: Any, axis: int = ..., order: int = ...): ...
