# Stubs for tensorflow.python.keras.utils.vis_utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

def model_to_dot(model: Any, show_shapes: bool = ..., show_layer_names: bool = ..., rankdir: str = ...): ...
def plot_model(model: Any, to_file: str = ..., show_shapes: bool = ..., show_layer_names: bool = ..., rankdir: str = ...) -> None: ...
