# Stubs for tensorflow.contrib.hooks.python.training (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.hooks.python.training.profiler_hook import ProfilerHook as ProfilerHook
