# Stubs for tensorflow.summary (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python import Event as Event, SessionLog as SessionLog, Summary as Summary, SummaryDescription as SummaryDescription, TaggedRunMetadata as TaggedRunMetadata
from tensorflow.python.ops.summary_ops import tensor_summary as tensor_summary
from tensorflow.python.summary.summary import FileWriter as FileWriter, FileWriterCache as FileWriterCache, audio as audio, get_summary_description as get_summary_description, histogram as histogram, image as image, merge as merge, merge_all as merge_all, scalar as scalar, text as text
