# Stubs for tensorflow._api.v1.keras.metrics (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.losses import KLD as KLD, MAE as MAE, MAPE as MAPE, MSE as MSE, MSLE as MSLE, binary_crossentropy as binary_crossentropy, categorical_crossentropy as categorical_crossentropy, cosine as cosine, hinge as hinge, poisson as poisson, sparse_categorical_crossentropy as sparse_categorical_crossentropy, squared_hinge as squared_hinge
from tensorflow.python.keras.metrics import binary_accuracy as binary_accuracy, categorical_accuracy as categorical_accuracy, deserialize as deserialize, get as get, serialize as serialize, sparse_categorical_accuracy as sparse_categorical_accuracy, sparse_top_k_categorical_accuracy as sparse_top_k_categorical_accuracy, top_k_categorical_accuracy as top_k_categorical_accuracy
