# Stubs for tensorflow.contrib.resampler.ops.gen_resampler_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from collections import namedtuple as namedtuple
from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def resampler(data: Any, warp: Any, name: Optional[Any] = ...): ...
def resampler_eager_fallback(data: Any, warp: Any, name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...

# _ResamplerGradOutput = namedtuple('ResamplerGrad', <ERROR>)

def resampler_grad(data: Any, warp: Any, grad_output: Any, name: Optional[Any] = ...): ...
def resampler_grad_eager_fallback(data: Any, warp: Any, grad_output: Any, name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...
