# Stubs for tensorflow.contrib.gan.python.estimator.python.head_impl (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.estimator.canned import head as head
from tensorflow.python.estimator.export import export_output as export_output
from tensorflow.python.framework import ops as ops
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

def gan_head(generator_loss_fn: Any, discriminator_loss_fn: Any, generator_optimizer: Any, discriminator_optimizer: Any, use_loss_summaries: bool = ..., get_hooks_fn: Any = ..., get_eval_metric_ops_fn: Optional[Any] = ..., name: Optional[Any] = ...): ...

class GANHead(head._Head):
    def __init__(self, generator_loss_fn: Any, discriminator_loss_fn: Any, generator_optimizer: Any, discriminator_optimizer: Any, use_loss_summaries: bool = ..., get_hooks_fn: Optional[Any] = ..., get_eval_metric_ops_fn: Optional[Any] = ..., name: Optional[Any] = ...) -> None: ...
    @property
    def name(self): ...
    @property
    def logits_dimension(self) -> None: ...
    def create_loss(self, features: Any, mode: Any, logits: Any, labels: Any): ...
    def create_estimator_spec(self, features: Any, mode: Any, logits: Any, labels: Optional[Any] = ..., train_op_fn: Any = ...): ...
