# Stubs for tensorflow.contrib.gan.python.estimator.python.stargan_estimator_impl (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import enum as enum
from tensorflow.python.estimator import estimator as estimator
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import variable_scope as variable_scope
from typing import Any as Any, Optional as Optional

class SummaryType(enum.IntEnum):
    NONE: int = ...
    VARIABLES: int = ...
    IMAGES: int = ...
    IMAGE_COMPARISON: int = ...

class StarGANEstimator(estimator.Estimator):
    def __init__(self, model_dir: Optional[Any] = ..., generator_fn: Optional[Any] = ..., discriminator_fn: Optional[Any] = ..., loss_fn: Optional[Any] = ..., generator_optimizer: Optional[Any] = ..., discriminator_optimizer: Optional[Any] = ..., get_hooks_fn: Optional[Any] = ..., get_eval_metric_ops_fn: Optional[Any] = ..., add_summaries: Optional[Any] = ..., use_loss_summaries: bool = ..., config: Optional[Any] = ...) -> None: ...
