# Stubs for tensorflow.python.autograph.pyct.origin_info (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.autograph.pyct import anno as anno, ast_util as ast_util, parser as parser
from tensorflow.python.util import tf_inspect as tf_inspect
from typing import Any as Any, Optional as Optional

class LineLocation: ...

class Location:
    @property
    def line_loc(self): ...

class OriginInfo:
    def as_frame(self): ...

def create_source_map(nodes: Any, code: Any, filename: Any, indices_in_code: Any): ...
def resolve(nodes: Any, source: Any, function: Optional[Any] = ...) -> None: ...
