# Stubs for tensorflow.contrib.layers.python.layers.optimizers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, clip_ops as clip_ops, control_flow_ops as control_flow_ops, init_ops as init_ops, math_ops as math_ops, random_ops as random_ops
from tensorflow.python.summary import summary as summary
from tensorflow.python.training import moving_averages as moving_averages
from typing import Any as Any, Optional as Optional

OPTIMIZER_CLS_NAMES: Any
OPTIMIZER_SUMMARIES: Any

def optimize_loss(loss: Any, global_step: Any, learning_rate: Any, optimizer: Any, gradient_noise_scale: Optional[Any] = ..., gradient_multipliers: Optional[Any] = ..., clip_gradients: Optional[Any] = ..., learning_rate_decay_fn: Optional[Any] = ..., update_ops: Optional[Any] = ..., variables: Optional[Any] = ..., name: Optional[Any] = ..., summaries: Optional[Any] = ..., colocate_gradients_with_ops: bool = ..., increment_global_step: bool = ...): ...
def adaptive_clipping_fn(std_factor: float = ..., decay: float = ..., static_max_norm: Optional[Any] = ..., global_step: Optional[Any] = ..., report_summary: bool = ..., epsilon: float = ..., name: Optional[Any] = ...): ...
