# Stubs for tensorflow.python.autograph.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns as control_dependency_on_returns
from tensorflow.python.autograph.utils.misc import alias_tensors as alias_tensors
from tensorflow.python.autograph.utils.multiple_dispatch import run_cond as run_cond
from tensorflow.python.autograph.utils.py_func import wrap_py_func as wrap_py_func
from tensorflow.python.autograph.utils.tensor_list import dynamic_list_append as dynamic_list_append
from tensorflow.python.autograph.utils.testing import fake_tf as fake_tf
from tensorflow.python.autograph.utils.type_check import is_tensor as is_tensor
