# Stubs for tensorflow.python.autograph.utils.py_func (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, tensor_util as tensor_util
from tensorflow.python.ops import script_ops as script_ops
from typing import Any as Any, Optional as Optional

class MatchDType: ...

def wrap_py_func(f: Any, return_dtypes: Any, args: Any, kwargs: Optional[Any] = ..., use_dummy_return: bool = ...): ...
