# Stubs for tensorflow.python.tools.selective_registration_header_lib (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.core.framework import graph_pb2 as graph_pb2
from tensorflow.python import pywrap_tensorflow as pywrap_tensorflow
from tensorflow.python.platform import gfile as gfile, tf_logging as tf_logging
from typing import Any as Any

OPS_WITHOUT_KERNEL_WHITELIST: Any

def get_ops_and_kernels(proto_fileformat: Any, proto_files: Any, default_ops_str: Any): ...
def get_header_from_ops_and_kernels(ops_and_kernels: Any, include_all_ops_and_kernels: Any): ...
def get_header(graphs: Any, proto_fileformat: str = ..., default_ops: str = ...): ...
