# Stubs for tensorflow.contrib.saved_model (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.saved_model.python.saved_model.keras_saved_model import *
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
