# Stubs for tensorflow._api.v1.keras.wrappers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow._api.v1.keras.wrappers import scikit_learn as scikit_learn
