# Stubs for tensorflow._api.v1.sparse (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python import SparseConditionalAccumulator as SparseConditionalAccumulator, SparseTensor as SparseTensor
