# Stubs for tensorflow.core.framework.attr_value_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
AttrValue: Any
NameAttrList: Any
