# Stubs for tensorflow.core.framework.device_attributes_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
InterconnectLink: Any
LocalLinks: Any
DeviceLocality: Any
DeviceAttributes: Any
