# Stubs for tensorflow.core.framework.function_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
FunctionDefLibrary: Any
FunctionDef: Any
GradientDef: Any
