# Stubs for tensorflow.core.framework.graph_transfer_info_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
GraphTransferNodeInput: Any
GraphTransferNodeInfo: Any
GraphTransferConstNodeInfo: Any
GraphTransferNodeInputInfo: Any
GraphTransferNodeOutputInfo: Any
GraphTransferGraphInputNodeInfo: Any
GraphTransferGraphOutputNodeInfo: Any
GraphTransferInfo: Any
