# Stubs for tensorflow.core.framework.remote_fused_graph_execute_info_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
RemoteFusedGraphExecuteInfo: Any
