# Stubs for tensorflow.core.framework.summary_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
SummaryDescription: Any
HistogramProto: Any
SummaryMetadata: Any
Summary: Any
