# Stubs for tensorflow.contrib.proto.python.ops.encode_proto_op (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.proto.python.ops.gen_encode_proto_op import encode_proto as encode_proto
from tensorflow.python.framework import ops as ops
