# Stubs for tensorflow.python.debug.cli.cli_test_utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

def assert_lines_equal_ignoring_whitespace(test: Any, expected_lines: Any, actual_lines: Any) -> None: ...
def assert_array_lines_close(test: Any, expected_array: Any, array_lines: Any) -> None: ...
