# Stubs for tensorflow.python.debug.cli.offline_analyzer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.debug.cli import analyzer_cli as analyzer_cli
from tensorflow.python.debug.lib import debug_data as debug_data
from tensorflow.python.platform import app as app
from typing import Any as Any

def main(_: Any) -> None: ...
