# Stubs for tensorflow.contrib.boosted_trees.estimator_batch.custom_export_strategy (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.boosted_trees.proto import tree_config_pb2 as tree_config_pb2
from tensorflow.contrib.boosted_trees.python.training.functions import gbdt_batch as gbdt_batch
from tensorflow.contrib.decision_trees.proto import generic_tree_model_extensions_pb2 as generic_tree_model_extensions_pb2, generic_tree_model_pb2 as generic_tree_model_pb2
from tensorflow.contrib.learn.python.learn import export_strategy as export_strategy
from tensorflow.contrib.learn.python.learn.utils import saved_model_export_utils as saved_model_export_utils
from tensorflow.python.framework import ops as ops
from tensorflow.python.platform import gfile as gfile
from tensorflow.python.saved_model import tag_constants as tag_constants
from tensorflow.python.util import compat as compat
from typing import Any as Any, Optional as Optional

def make_custom_export_strategy(name: Any, convert_fn: Any, feature_columns: Any, export_input_fn: Any, use_core_columns: bool = ...): ...
def convert_to_universal_format(dtec: Any, sorted_feature_names: Any, num_dense: Any, num_sparse_float: Any, num_sparse_int: Any, feature_name_to_proto: Optional[Any] = ...): ...
