# Stubs for tensorflow.contrib.boosted_trees.estimator_batch.model (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib import learn as learn
from tensorflow.contrib.boosted_trees.estimator_batch import estimator_utils as estimator_utils, trainer_hooks as trainer_hooks
from tensorflow.contrib.boosted_trees.python.ops import model_ops as model_ops
from tensorflow.contrib.boosted_trees.python.training.functions import gbdt_batch as gbdt_batch
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import state_ops as state_ops
from tensorflow.python.training import training_util as training_util
from typing import Any as Any

class ModelBuilderOutputType:
    MODEL_FN_OPS: int = ...
    ESTIMATOR_SPEC: int = ...

def model_builder(features: Any, labels: Any, mode: Any, params: Any, config: Any, output_type: Any = ...): ...
def ranking_model_builder(features: Any, labels: Any, mode: Any, params: Any, config: Any, output_type: Any = ...): ...
