# Stubs for tensorflow.contrib.slim.python.slim.queues (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.training import coordinator as coordinator
from typing import Any as Any

class NestedQueueRunnerError(Exception): ...

def QueueRunners(session: Any) -> None: ...
