# Stubs for tensorflow.python.training.checkpointable.tracking (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.training.checkpointable import base as base, data_structures as data_structures
from typing import Any as Any

class NotCheckpointable: ...

class Checkpointable(base.CheckpointableBase):
    def __setattr__(self, name: Any, value: Any) -> None: ...
