# Stubs for tensorflow.python.tools.strip_unused (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes
from tensorflow.python.platform import app as app
from tensorflow.python.tools import strip_unused_lib as strip_unused_lib
from typing import Any as Any

FLAGS: Any

def main(unused_args: Any) -> None: ...
