# Stubs for tensorflow.contrib.layers.python.layers.encoders (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.framework.python.ops import variables as variables
from tensorflow.contrib.layers.python.ops import sparse_ops as sparse_ops
from tensorflow.python.framework import sparse_tensor as sparse_tensor
from tensorflow.python.ops import embedding_ops as embedding_ops, math_ops as math_ops, variable_scope as variable_scope
from typing import Any as Any, Optional as Optional

def bow_encoder(ids: Any, vocab_size: Any, embed_dim: Any, sparse_lookup: bool = ..., initializer: Optional[Any] = ..., regularizer: Optional[Any] = ..., trainable: bool = ..., scope: Optional[Any] = ..., reuse: Optional[Any] = ...): ...
def embed_sequence(ids: Any, vocab_size: Optional[Any] = ..., embed_dim: Optional[Any] = ..., unique: bool = ..., initializer: Optional[Any] = ..., regularizer: Optional[Any] = ..., trainable: bool = ..., scope: Optional[Any] = ..., reuse: Optional[Any] = ...): ...
