# Stubs for tensorflow.contrib.layers.python.layers.summaries (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import standard_ops as standard_ops
from tensorflow.python.summary import summary as summary
from typing import Any as Any, Optional as Optional

def summarize_activation(op: Any): ...
def summarize_tensor(tensor: Any, tag: Optional[Any] = ...): ...
def summarize_tensors(tensors: Any, summarizer: Any = ...): ...
def summarize_collection(collection: Any, name_filter: Optional[Any] = ..., summarizer: Any = ...): ...

summarize_variables: Any
summarize_weights: Any
summarize_biases: Any

def summarize_activations(name_filter: Optional[Any] = ..., summarizer: Any = ...): ...
