# Stubs for tensorflow.contrib.hooks.python.training.profiler_hook (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.training import basic_session_run_hooks as basic_session_run_hooks

ProfilerHook = basic_session_run_hooks.ProfilerHook
