# Stubs for tensorflow.contrib.lite.toco.python.tensorflow_wrap_toco (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

def swig_import_helper(): ...

class _object: ...

def TocoConvert(model_flags_proto_txt_raw: Any, toco_flags_proto_txt_raw: Any, input_contents_txt_raw: Any, extended_return: bool = ...): ...

TocoConvert: Any
