# Stubs for tensorflow.python.tools.api.generator.doc_srcs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from collections import namedtuple as namedtuple
from tensorflow.python.util import tf_export as tf_export
from typing import Any as Any

DocSource = namedtuple('DocSource', ['docstring', 'docstring_module_name'])

def get_doc_sources(api_name: Any): ...
