# Stubs for tensorflow.contrib.input_pipeline.ops.gen_input_pipeline_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def obtain_next(list: Any, counter: Any, name: Optional[Any] = ...): ...
