# Stubs for tensorflow.contrib.batching (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.batching.python.ops.batch_ops import batch_function as batch_function
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
