# Stubs for tensorflow.python.keras.applications.vgg19 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.applications import keras_modules_injection as keras_modules_injection
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

def VGG19(*args: Any, **kwargs: Any): ...
def decode_predictions(*args: Any, **kwargs: Any): ...
def preprocess_input(*args: Any, **kwargs: Any): ...
