# Stubs for tensorflow.keras.applications.densenet (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.applications import DenseNet121 as DenseNet121, DenseNet169 as DenseNet169, DenseNet201 as DenseNet201
from tensorflow.python.keras.applications.densenet import decode_predictions as decode_predictions, preprocess_input as preprocess_input
