# Stubs for tensorflow.contrib.bigtable (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.bigtable.python.ops.bigtable_api import BigtableClient as BigtableClient, BigtableTable as BigtableTable
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
