# Stubs for tensorflow.python.saved_model.main_op_impl (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import control_flow_ops as control_flow_ops, lookup_ops as lookup_ops, variables as variables
from tensorflow.python.util import deprecation as deprecation
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

def main_op(): ...
def main_op_with_restore(restore_op_name: Any): ...
