# Stubs for tensorflow.python.saved_model.saved_model (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.saved_model.simple_save import *
from tensorflow.python.saved_model import builder as builder, constants as constants, loader as loader, main_op as main_op, signature_constants as signature_constants, signature_def_utils as signature_def_utils, tag_constants as tag_constants, utils as utils
