# Stubs for tensorflow.python.saved_model.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.saved_model.utils_impl import build_tensor_info as build_tensor_info, get_tensor_from_tensor_info as get_tensor_from_tensor_info
