# Stubs for tensorflow.contrib.gan.python.features.python.random_tensor_pool_impl (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, data_flow_ops as data_flow_ops, random_ops as random_ops
from tensorflow.python.util import nest as nest
from typing import Any as Any

def tensor_pool(input_values: Any, pool_size: int = ..., pooling_probability: float = ..., name: str = ...): ...
