# Stubs for tensorflow.contrib.gan.python.features.python.virtual_batchnorm (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.gan.python.features.python.virtual_batchnorm_impl import *
from tensorflow.contrib.gan.python.features.python import virtual_batchnorm_impl as virtual_batchnorm_impl
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented

# Names in __all__ with no definition:
#   VBN
