# Stubs for tensorflow.contrib.gan.python.estimator (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.gan.python.estimator.python.gan_estimator import *
from tensorflow.contrib.gan.python.estimator.python.head import *
from tensorflow.contrib.gan.python.estimator.python.stargan_estimator import *
from tensorflow.contrib.gan.python.estimator.python import gan_estimator as gan_estimator, head as head, stargan_estimator as stargan_estimator
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
