# Stubs for tensorflow.contrib.tpu.proto.optimization_parameters_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
ClippingLimits: Any
DynamicLearningRate: Any
LearningRate: Any
AdagradParameters: Any
StochasticGradientDescentParameters: Any
FtrlParameters: Any
AdamParameters: Any
MomentumParameters: Any
RmsPropParameters: Any
CenteredRmsPropParameters: Any
MdlAdagradLightParameters: Any
AdadeltaParameters: Any
ProximalAdagradParameters: Any
OptimizationParameters: Any
StateVariableSpecification: Any
