# Stubs for tensorflow.contrib.framework.python.framework.tensor_util (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, ops as ops, sparse_tensor as sparse_tensor, tensor_shape as tensor_shape, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, control_flow_ops as control_flow_ops, math_ops as math_ops
from tensorflow.python.util.deprecation import deprecated as deprecated
from typing import Any as Any, Optional as Optional

is_tensor = tensor_util.is_tensor
assert_same_float_dtype = check_ops.assert_same_float_dtype
assert_scalar = check_ops.assert_scalar
convert_to_tensor_or_sparse_tensor = sparse_tensor.convert_to_tensor_or_sparse_tensor

def reduce_sum_n(tensors: Any, name: Optional[Any] = ...): ...
def remove_squeezable_dimensions(predictions: Any, labels: Any, name: Optional[Any] = ...): ...
def with_same_shape(expected_tensor: Any, tensor: Any): ...
def with_shape(expected_shape: Any, tensor: Any): ...
def assert_scalar_int(tensor: Any, name: Optional[Any] = ...): ...
