# Stubs for tensorflow._api.v1.keras.constraints (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.constraints import Constraint as Constraint, MaxNorm as MaxNorm, MinMaxNorm as MinMaxNorm, NonNeg as NonNeg, UnitNorm as UnitNorm, deserialize as deserialize, get as get, serialize as serialize
