# Stubs for tensorflow.contrib.solvers.python.ops.lanczos (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.solvers.python.ops import util as util
from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, math_ops as math_ops, random_ops as random_ops, tensor_array_ops as tensor_array_ops
from typing import Any as Any, Optional as Optional

def lanczos_bidiag(operator: Any, k: Any, orthogonalize: bool = ..., starting_vector: Optional[Any] = ..., name: str = ...): ...
def bidiag_matmul(matrix: Any, alpha: Any, beta: Any, adjoint_b: bool = ..., name: str = ...): ...
