# Stubs for tensorflow.contrib.solvers.python.ops.least_squares (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.solvers.python.ops import util as util
from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, math_ops as math_ops
from typing import Any as Any

def cgls(operator: Any, rhs: Any, tol: float = ..., max_iter: int = ..., name: str = ...): ...
