# Stubs for tensorflow.contrib.solvers.python.ops.linear_equations (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.solvers.python.ops import util as util
from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, linalg_ops as linalg_ops, math_ops as math_ops
from typing import Any as Any, Optional as Optional

def conjugate_gradient(operator: Any, rhs: Any, preconditioner: Optional[Any] = ..., x: Optional[Any] = ..., tol: float = ..., max_iter: int = ..., name: str = ...): ...
