# Stubs for tensorflow.contrib.opt.python.training.external_optimizer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, gradients as gradients, variables as variables
from typing import Any as Any, Optional as Optional

class ExternalOptimizerInterface:
    optimizer_kwargs: Any = ...
    def __init__(self, loss: Any, var_list: Optional[Any] = ..., equalities: Optional[Any] = ..., inequalities: Optional[Any] = ..., var_to_bounds: Optional[Any] = ..., **optimizer_kwargs: Any) -> None: ...
    def minimize(self, session: Optional[Any] = ..., feed_dict: Optional[Any] = ..., fetches: Optional[Any] = ..., step_callback: Optional[Any] = ..., loss_callback: Optional[Any] = ..., **run_kwargs: Any) -> None: ...

class ScipyOptimizerInterface(ExternalOptimizerInterface): ...
