# Stubs for tensorflow.contrib.opt.python.training.moving_average_optimizer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import control_flow_ops as control_flow_ops, variables as variables
from tensorflow.python.training import moving_averages as moving_averages, optimizer as optimizer, saver as saver
from typing import Any as Any, Optional as Optional

class MovingAverageOptimizer(optimizer.Optimizer):
    def __init__(self, opt: Any, average_decay: float = ..., num_updates: Optional[Any] = ..., sequential_update: bool = ...) -> None: ...
    def compute_gradients(self, *args: Any, **kwargs: Any): ...
    def apply_gradients(self, grads_and_vars: Any, global_step: Optional[Any] = ..., name: Optional[Any] = ...): ...
    def swapping_saver(self, var_list: Optional[Any] = ..., name: str = ..., **kwargs: Any): ...
