# Stubs for tensorflow.keras.applications.nasnet (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.applications import NASNetLarge as NASNetLarge, NASNetMobile as NASNetMobile
from tensorflow.python.keras.applications.nasnet import decode_predictions as decode_predictions, preprocess_input as preprocess_input
