# Stubs for tensorflow.contrib.rpc.python.kernel_tests.test_example_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
TestCase: Any
