# Stubs for tensorflow.python.autograph.operators (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.autograph.operators.control_flow import for_stmt as for_stmt, while_stmt as while_stmt
from tensorflow.python.autograph.operators.data_structures import ListPopOpts as ListPopOpts, ListStackOpts as ListStackOpts, list_append as list_append, list_pop as list_pop, list_stack as list_stack, new_list as new_list
from tensorflow.python.autograph.operators.py_builtins import float_ as float_, int_ as int_, len_ as len_, print_ as print_, range_ as range_
from tensorflow.python.autograph.operators.slices import GetItemOpts as GetItemOpts, get_item as get_item, set_item as set_item
