# Stubs for tensorflow.python.autograph.operators.slices (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, tensor_util as tensor_util
from tensorflow.python.ops import gen_string_ops as gen_string_ops, list_ops as list_ops, tensor_array_ops as tensor_array_ops
from typing import Any as Any

class GetItemOpts: ...

def get_item(target: Any, i: Any, opts: Any): ...
def set_item(target: Any, i: Any, x: Any): ...
