# Stubs for tensorflow.contrib.bayesflow.python.ops.monte_carlo (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.bayesflow.python.ops.monte_carlo_impl import *
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
