# Stubs for tensorflow.contrib.framework.python.ops.checkpoint_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes
from tensorflow.python.ops import init_ops as init_ops
from tensorflow.python.training import checkpoint_ops as checkpoint_ops
from typing import Any as Any, Optional as Optional

load_and_remap_matrix_initializer: Any
load_embedding_initializer: Any

def load_linear_multiclass_bias_initializer(ckpt_path: Any, bias_tensor_name: Any, new_class_vocab_size: Any, old_class_vocab_file: Any, new_class_vocab_file: Any, num_class_oov_buckets: int = ..., initializer: Optional[Any] = ..., max_rows_in_memory: int = ...): ...
def load_variable_slot_initializer(ckpt_path: Any, old_tensor_name: Any, primary_partition_info: Any, new_row_vocab_size: Any, new_col_vocab_size: Any, old_row_vocab_file: Optional[Any] = ..., new_row_vocab_file: Optional[Any] = ..., old_col_vocab_file: Optional[Any] = ..., new_col_vocab_file: Optional[Any] = ..., num_row_oov_buckets: int = ..., num_col_oov_buckets: int = ..., initializer: Optional[Any] = ..., max_rows_in_memory: int = ...): ...
