# Stubs for tensorflow.contrib.framework.python.ops.gen_variable_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def zero_initializer(ref: Any, name: Optional[Any] = ...): ...
def zero_var_initializer(var: Any, dtype: Any, shape: Any, name: Optional[Any] = ...): ...
def zero_var_initializer_eager_fallback(var: Any, dtype: Any, shape: Any, name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...
