# Stubs for tensorflow.contrib.losses (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.losses.python.losses import *
from tensorflow.contrib.losses.python import metric_learning as metric_learning
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
