# Stubs for tensorflow.contrib.ffmpeg (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.ffmpeg.ffmpeg_ops import decode_audio as decode_audio, decode_video as decode_video, encode_audio as encode_audio
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
