# Stubs for tensorflow.contrib.keras.api.keras.optimizers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.optimizers import Adadelta as Adadelta, Adagrad as Adagrad, Adam as Adam, Adamax as Adamax, Nadam as Nadam, Optimizer as Optimizer, RMSprop as RMSprop, SGD as SGD, deserialize as deserialize, get as get, serialize as serialize
