# Stubs for tensorflow.core.protobuf.meta_graph_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
MetaGraphDef: Any
CollectionDef: Any
TensorInfo: Any
SignatureDef: Any
AssetFileDef: Any
