# Stubs for tensorflow.core.protobuf.rewriter_config_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
AutoParallelOptions: Any
ScopedAllocatorOptions: Any
RewriterConfig: Any
