# Stubs for tensorflow.contrib.keras.api.keras.applications.vgg19 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.applications.vgg19 import VGG19 as VGG19, decode_predictions as decode_predictions, preprocess_input as preprocess_input
