# Stubs for tensorflow.python.framework.smart_cond (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops, tensor_util as tensor_util
from tensorflow.python.ops import control_flow_ops as control_flow_ops
from typing import Any as Any, Optional as Optional

def smart_cond(pred: Any, true_fn: Optional[Any] = ..., false_fn: Optional[Any] = ..., name: Optional[Any] = ...): ...
def smart_constant_value(pred: Any): ...
def smart_case(pred_fn_pairs: Any, default: Optional[Any] = ..., exclusive: bool = ..., name: str = ...): ...
