# Stubs for tensorflow.compiler.xla.service.hlo_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
HloInstructionProto: Any
HloComputationProto: Any
HloScheduleProto: Any
HloModuleProto: Any
LogicalBufferProto: Any
BufferAllocationProto: Any
HeapSimulatorTrace: Any
HloModuleGroupProto: Any
BufferAssignmentProto: Any
HloProto: Any
HloSnapshot: Any
