# Stubs for tensorflow.contrib.data.python.ops.get_single_element (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.ops import dataset_ops as dataset_ops
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any

def get_single_element(dataset: Any): ...
def reduce_dataset(dataset: Any, reducer: Any): ...
