# Stubs for tensorflow.contrib.data.python.ops.grouping (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.experimental.ops import grouping as grouping
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

def group_by_reducer(key_func: Any, reducer: Any): ...
def group_by_window(key_func: Any, reduce_func: Any, window_size: Optional[Any] = ..., window_size_func: Optional[Any] = ...): ...
def bucket_by_sequence_length(element_length_func: Any, bucket_boundaries: Any, bucket_batch_sizes: Any, padded_shapes: Optional[Any] = ..., padding_values: Optional[Any] = ..., pad_to_bucket_boundary: bool = ..., no_padding: bool = ...): ...

class Reducer(grouping.Reducer):
    def __init__(self, init_func: Any, reduce_func: Any, finalize_func: Any) -> None: ...
