# Stubs for tensorflow.contrib.data.python.ops.prefetching_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.experimental.ops import prefetching_ops as prefetching_ops
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

def prefetch_to_device(device: Any, buffer_size: Optional[Any] = ...): ...
def copy_to_device(target_device: Any, source_device: str = ...): ...
