# Stubs for tensorflow.contrib.data.python.ops.threadpool (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.experimental.ops.threadpool import PrivateThreadPool as PrivateThreadPool, override_threadpool as override_threadpool
