# Stubs for tensorflow._api.v1.spectral (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python import fft as fft, fft2d as fft2d, fft3d as fft3d, ifft as ifft, ifft2d as ifft2d, ifft3d as ifft3d
from tensorflow.python.ops.spectral_ops import dct as dct, idct as idct, irfft as irfft, irfft2d as irfft2d, irfft3d as irfft3d, rfft as rfft, rfft2d as rfft2d, rfft3d as rfft3d
