# Stubs for tensorflow.python.autograph.utils.context_managers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import tensor_array_ops as tensor_array_ops
from typing import Any as Any

def control_dependency_on_returns(return_value: Any): ...
