# Stubs for tensorflow.python.autograph.utils.misc (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops
from typing import Any as Any

def alias_tensors(*args: Any): ...
