# Stubs for tensorflow.python.autograph.utils.multiple_dispatch (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.autograph.utils.type_check import is_tensor as is_tensor
from tensorflow.python.ops import control_flow_ops as control_flow_ops
from typing import Any as Any

def run_cond(condition: Any, true_fn: Any, false_fn: Any): ...
def py_cond(condition: Any, true_fn: Any, false_fn: Any): ...
