# Stubs for tensorflow.python.autograph.utils.tensors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, tensor_util as tensor_util
from tensorflow.python.ops import tensor_array_ops as tensor_array_ops
from typing import Any as Any

def is_tensor_array(t: Any): ...
def is_tensor_list(t: Any): ...
