# Stubs for tensorflow.python.autograph.utils.testing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import math_ops as math_ops

def fake_tf(): ...
