# Stubs for tensorflow.python.autograph.utils.type_check (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import tensor_util as tensor_util
from typing import Any as Any

def is_tensor(*args: Any): ...
