# Stubs for tensorflow.core.framework.log_memory_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
MemoryLogStep: Any
MemoryLogTensorAllocation: Any
MemoryLogTensorDeallocation: Any
MemoryLogTensorOutput: Any
MemoryLogRawAllocation: Any
MemoryLogRawDeallocation: Any
