# Stubs for tensorflow.core.framework.op_def_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
OpDef: Any
OpDeprecation: Any
OpList: Any
