# Stubs for tensorflow.core.framework.resource_handle_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
ResourceHandleProto: Any
