# Stubs for tensorflow.core.framework.step_stats_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
AllocationRecord: Any
AllocatorMemoryUsed: Any
NodeOutput: Any
MemoryStats: Any
NodeExecStats: Any
DeviceStepStats: Any
StepStats: Any
