# Stubs for tensorflow.python.keras.preprocessing.sequence (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import abc as abc
from keras_preprocessing import sequence as sequence
from tensorflow.python.keras import utils as utils
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

pad_sequences: Any
make_sampling_table: Any
skipgrams: Any

class TimeseriesGenerator(sequence.TimeseriesGenerator, utils.Sequence, metaclass=abc.ABCMeta): ...
