# Stubs for tensorflow.python.keras.preprocessing.text (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

text_to_word_sequence: Any
one_hot: Any
hashing_trick: Any
Tokenizer: Any
