# Stubs for tensorflow.contrib.predictor.predictor_factories (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.predictor import contrib_estimator_predictor as contrib_estimator_predictor, core_estimator_predictor as core_estimator_predictor, saved_model_predictor as saved_model_predictor
from typing import Any as Any, Optional as Optional

def from_contrib_estimator(estimator: Any, prediction_input_fn: Any, input_alternative_key: Optional[Any] = ..., output_alternative_key: Optional[Any] = ..., graph: Optional[Any] = ..., config: Optional[Any] = ...): ...
def from_estimator(estimator: Any, serving_input_receiver_fn: Any, output_key: Optional[Any] = ..., graph: Optional[Any] = ..., config: Optional[Any] = ...): ...
def from_saved_model(export_dir: Any, signature_def_key: Optional[Any] = ..., signature_def: Optional[Any] = ..., input_names: Optional[Any] = ..., output_names: Optional[Any] = ..., tags: Optional[Any] = ..., graph: Optional[Any] = ..., config: Optional[Any] = ...): ...
