# Stubs for tensorflow.contrib.tfprof.model_analyzer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.profiler import tfprof_logger as tfprof_logger
from tensorflow.python.profiler.model_analyzer import ALL_ADVICE as ALL_ADVICE, Profiler as Profiler
from tensorflow.python.profiler.profile_context import ProfileContext as ProfileContext
from tensorflow.python.util.deprecation import deprecated as deprecated
from typing import Any as Any, Optional as Optional

TRAINABLE_VARS_PARAMS_STAT_OPTIONS: Any
FLOAT_OPS_OPTIONS: Any
PRINT_ALL_TIMING_MEMORY: Any

def advise(graph: Any, run_meta: Optional[Any] = ..., tfprof_options: Any = ...): ...
def print_model_analysis(graph: Any, run_meta: Optional[Any] = ..., op_log: Optional[Any] = ..., tfprof_cmd: str = ..., tfprof_options: Any = ...): ...
