# Stubs for tensorflow.contrib.hadoop (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.hadoop.python.ops.hadoop_dataset_ops import SequenceFileDataset as SequenceFileDataset
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
