# Stubs for tensorflow._api.v1.keras.activations (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.activations import deserialize as deserialize, elu as elu, get as get, hard_sigmoid as hard_sigmoid, linear as linear, relu as relu, selu as selu, serialize as serialize, sigmoid as sigmoid, softmax as softmax, softplus as softplus, softsign as softsign, tanh as tanh
