# Stubs for tensorflow.contrib.input_pipeline.python.ops.input_pipeline_ops_test (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.input_pipeline.python.ops import input_pipeline_ops as input_pipeline_ops
from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, errors as errors
from tensorflow.python.ops import state_ops as state_ops, variables as variables
from tensorflow.python.platform import test as test

class InputPipelineOpsTest(test.TestCase):
    def testObtainNext(self) -> None: ...
    def testSeekNext(self) -> None: ...
    def testSeekNextLimitEpochs(self) -> None: ...
    def testSeekNextLimitEpochsThree(self) -> None: ...
