# Stubs for tensorflow.contrib.tensorboard.plugins.projector.projector_config_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
SpriteMetadata: Any
EmbeddingInfo: Any
ProjectorConfig: Any
