# Stubs for tensorflow._api.v1.python_io (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.lib.io.python_io import TFRecordCompressionType as TFRecordCompressionType, TFRecordOptions as TFRecordOptions, TFRecordWriter as TFRecordWriter, tf_record_iterator as tf_record_iterator
