# Stubs for tensorflow.contrib.periodic_resample.python.ops.periodic_resample_op (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.periodic_resample.python.ops import gen_periodic_resample_op as gen_periodic_resample_op
from tensorflow.contrib.periodic_resample.python.ops.gen_periodic_resample_op import periodic_resample as periodic_resample, periodic_resample_op_grad as periodic_resample_op_grad
from tensorflow.contrib.util import loader as loader
from tensorflow.python.framework import ops as ops
from tensorflow.python.platform import resource_loader as resource_loader
