# Stubs for tensorflow.contrib.boosted_trees.estimator_batch (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.boosted_trees.estimator_batch import *
