# Stubs for tensorflow.contrib.boosted_trees.estimator_batch.custom_loss_head (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.learn.python.learn.estimators import head as head_lib
from tensorflow.python.framework import dtypes as dtypes
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops
from typing import Any as Any, Optional as Optional

class CustomLossHead(head_lib._RegressionHead):
    def __init__(self, loss_fn: Any, link_fn: Any, logit_dimension: Any, head_name: Optional[Any] = ..., weight_column_name: Optional[Any] = ..., metrics_fn: Optional[Any] = ...) -> None: ...
