# Stubs for tensorflow.python.summary.writer.writer_cache (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.summary.writer.writer import FileWriter as FileWriter
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

class FileWriterCache:
    @staticmethod
    def clear() -> None: ...
    @staticmethod
    def get(logdir: Any): ...
