# Stubs for tensorflow.contrib.distributions.python.ops.independent (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, ops as ops, tensor_shape as tensor_shape, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, math_ops as math_ops
from tensorflow.python.ops.distributions import distribution as distribution_lib, kullback_leibler as kullback_leibler
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class Independent(distribution_lib.Distribution):
    def __init__(self, distribution: Any, reinterpreted_batch_ndims: Optional[Any] = ..., validate_args: bool = ..., name: Optional[Any] = ...) -> None: ...
    @property
    def distribution(self): ...
    @property
    def reinterpreted_batch_ndims(self): ...
