# Stubs for tensorflow.contrib.distributions.python.ops.mixture (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops, tensor_shape as tensor_shape, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, data_flow_ops as data_flow_ops, math_ops as math_ops, nn_ops as nn_ops
from tensorflow.python.ops.distributions import categorical as categorical, distribution as distribution
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any

class Mixture(distribution.Distribution):
    def __init__(self, cat: Any, components: Any, validate_args: bool = ..., allow_nan_stats: bool = ..., use_static_graph: bool = ..., name: str = ...) -> None: ...
    @property
    def cat(self): ...
    @property
    def components(self): ...
    @property
    def num_components(self): ...
    def entropy_lower_bound(self, name: str = ...): ...
