# Stubs for tensorflow.contrib.distributions.python.ops.poisson_lognormal (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.distributions.python.ops import distribution_util as distribution_util
from tensorflow.contrib.distributions.python.ops.bijectors.exp import Exp as Exp
from tensorflow.python.framework import dtypes as dtypes, ops as ops, tensor_shape as tensor_shape
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops, random_ops as random_ops
from tensorflow.python.ops.distributions import distribution as distribution_lib
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

def quadrature_scheme_lognormal_gauss_hermite(loc: Any, scale: Any, quadrature_size: Any, validate_args: bool = ..., name: Optional[Any] = ...): ...
def quadrature_scheme_lognormal_quantiles(loc: Any, scale: Any, quadrature_size: Any, validate_args: bool = ..., name: Optional[Any] = ...): ...

class PoissonLogNormalQuadratureCompound(distribution_lib.Distribution):
    def __init__(self, loc: Any, scale: Any, quadrature_size: int = ..., quadrature_fn: Any = ..., validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
    @property
    def mixture_distribution(self): ...
    @property
    def distribution(self): ...
    @property
    def loc(self): ...
    @property
    def scale(self): ...
    @property
    def quadrature_size(self): ...
