# Stubs for tensorflow.contrib.distributions.python.ops.relaxed_onehot_categorical (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.distributions.python.ops import bijectors as bijectors
from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, control_flow_ops as control_flow_ops, math_ops as math_ops, nn_ops as nn_ops, random_ops as random_ops
from tensorflow.python.ops.distributions import distribution as distribution, transformed_distribution as transformed_distribution
from tensorflow.python.util import deprecation as deprecation
from typing import Any as Any, Optional as Optional

class ExpRelaxedOneHotCategorical(distribution.Distribution):
    def __init__(self, temperature: Any, logits: Optional[Any] = ..., probs: Optional[Any] = ..., dtype: Optional[Any] = ..., validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
    @property
    def event_size(self): ...
    @property
    def temperature(self): ...
    @property
    def logits(self): ...
    @property
    def probs(self): ...

class RelaxedOneHotCategorical(transformed_distribution.TransformedDistribution):
    def __init__(self, temperature: Any, logits: Optional[Any] = ..., probs: Optional[Any] = ..., dtype: Optional[Any] = ..., validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
