# Stubs for tensorflow.contrib.distributions.python.ops.sample_stats (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, ops as ops, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, clip_ops as clip_ops, control_flow_ops as control_flow_ops, math_ops as math_ops, nn_ops as nn_ops, spectral_ops as spectral_ops
from tensorflow.python.ops.distributions import util as util
from typing import Any as Any, Optional as Optional

def auto_correlation(x: Any, axis: int = ..., max_lags: Optional[Any] = ..., center: bool = ..., normalize: bool = ..., name: str = ...): ...
def percentile(x: Any, q: Any, axis: Optional[Any] = ..., interpolation: Optional[Any] = ..., keep_dims: bool = ..., validate_args: bool = ..., name: Optional[Any] = ...): ...
