# Stubs for tensorflow.python.debug.examples.debug_errors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

def main(_: Any) -> None: ...
