# Stubs for tensorflow.python.ops.losses.losses (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops.losses.losses_impl import *
from tensorflow.python.ops.losses.util import *
