# Stubs for tensorflow.contrib.lite.toco.python._tensorflow_wrap_toco (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def SWIG_PyInstanceMethod_New(*args, **kwargs) -> Any: ...
def TocoConvert(*args, **kwargs) -> Any: ...
