# Stubs for tensorflow.contrib.lite.toco.python.toco_from_protos (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.lite.toco.python import tensorflow_wrap_toco as tensorflow_wrap_toco
from tensorflow.python.platform import app as app
from typing import Any as Any

FLAGS: Any

def execute(unused_args: Any) -> None: ...
def main() -> None: ...
