# Stubs for tensorflow.python.util.example_parser_configuration (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.core.example import example_parser_configuration_pb2 as example_parser_configuration_pb2
from tensorflow.python.framework import tensor_shape as tensor_shape, tensor_util as tensor_util
from typing import Any as Any

def extract_example_parser_configuration(parse_example_op: Any, sess: Any): ...
