# Stubs for tensorflow.python.util.serialization (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import tensor_shape as tensor_shape
from typing import Any as Any

def get_json_type(obj: Any): ...
