# Stubs for tensorflow.python.util.compat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

def as_bytes(bytes_or_text: Any, encoding: str = ...): ...
def as_text(bytes_or_text: Any, encoding: str = ...): ...
as_str = as_bytes
as_str = as_text

def as_str_any(value: Any): ...
def path_to_str(path: Any): ...

integral_types: Any
real_types: Any
complex_types: Any
bytes_or_text_types: Any
