# Stubs for tensorflow.python.util.compat_internal (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.compat import as_str_any as as_str_any
from typing import Any as Any

def path_to_str(path: Any): ...
