# Stubs for tensorflow.python.util.memory (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

def dismantle_ordered_dict(ordered_dict: Any) -> None: ...
