# Stubs for tensorflow.python.util.tf_contextlib (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util import tf_decorator as tf_decorator
from typing import Any as Any

def contextmanager(target: Any): ...
