# Stubs for tensorflow.python.data (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data import experimental as experimental
from tensorflow.python.data.ops.dataset_ops import Dataset as Dataset
from tensorflow.python.data.ops.iterator_ops import Iterator as Iterator
from tensorflow.python.data.ops.readers import FixedLengthRecordDataset as FixedLengthRecordDataset, TFRecordDataset as TFRecordDataset, TextLineDataset as TextLineDataset
