# Stubs for tensorflow.contrib.opt.python.training.ggt (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.optimizer_v2 import optimizer_v2 as optimizer_v2
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, linalg_ops as linalg_ops, math_ops as math_ops, state_ops as state_ops
from typing import Any as Any

class GGTOptimizer(optimizer_v2.OptimizerV2):
    index_dict: Any = ...
    shape_dict: Any = ...
    def __init__(self, learning_rate: float = ..., beta1: float = ..., use_locking: bool = ..., name: str = ..., window: int = ..., eps: float = ..., svd_eps: float = ..., sigma_eps: float = ...) -> None: ...
