# Stubs for tensorflow.contrib.opt.python.training.lars_optimizer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops import array_ops as array_ops, linalg_ops as linalg_ops, math_ops as math_ops
from tensorflow.python.training import optimizer as optimizer, training_ops as training_ops
from typing import Any as Any, Optional as Optional

class LARSOptimizer(optimizer.Optimizer):
    def __init__(self, learning_rate: Any, momentum: float = ..., weight_decay: float = ..., eeta: float = ..., epsilon: float = ..., name: str = ..., skip_list: Optional[Any] = ..., use_nesterov: bool = ...) -> None: ...
    def compute_lr(self, grad: Any, var: Any): ...
