# Stubs for tensorflow.contrib.opt.python.training.lazy_adam_optimizer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, math_ops as math_ops, resource_variable_ops as resource_variable_ops, state_ops as state_ops
from tensorflow.python.training import adam as adam

class LazyAdamOptimizer(adam.AdamOptimizer): ...
