# Stubs for tensorflow.contrib.opt.python.training.matrix_functions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops import control_flow_ops as control_flow_ops, linalg_ops as linalg_ops, math_ops as math_ops
from typing import Any as Any

def matrix_square_root(mat_a: Any, mat_a_size: Any, iter_count: int = ..., ridge_epsilon: float = ...): ...
def matrix_inverse_pth_root(mat_g: Any, mat_g_size: Any, alpha: Any, iter_count: int = ..., epsilon: float = ..., ridge_epsilon: float = ...): ...
