# Stubs for tensorflow.contrib.opt.python.training.nadam_optimizer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import control_flow_ops as control_flow_ops, math_ops as math_ops, state_ops as state_ops
from tensorflow.python.training import adam as adam, training_ops as training_ops

class NadamOptimizer(adam.AdamOptimizer): ...
