# Stubs for tensorflow.contrib.opt.python.training.powersign (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, math_ops as math_ops, state_ops as state_ops
from tensorflow.python.training import optimizer as optimizer, training_ops as training_ops
from typing import Any as Any, Optional as Optional

class PowerSignOptimizer(optimizer.Optimizer):
    def __init__(self, learning_rate: float = ..., base: Any = ..., beta: float = ..., sign_decay_fn: Optional[Any] = ..., use_locking: bool = ..., name: str = ...) -> None: ...
    def apply_gradients(self, grads_and_vars: Any, global_step: Optional[Any] = ..., name: Optional[Any] = ...): ...
