# Stubs for tensorflow.contrib.opt.python.training.reg_adagrad_optimizer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops import math_ops as math_ops
from tensorflow.python.training import adagrad as adagrad, training_ops as training_ops
from tensorflow.python.util import tf_contextlib as tf_contextlib
from typing import Any as Any

class RegAdagradOptimizer(adagrad.AdagradOptimizer):
    def __init__(self, learning_rate: Any, initial_accumulator_value: float = ..., use_locking: bool = ..., name: str = ...) -> None: ...
    def avoid_updating_slots(self) -> None: ...
