# Stubs for tensorflow.contrib.tensorboard.plugins (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.tensorboard.plugins import projector as projector
