# Stubs for tensorflow.sysconfig (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.platform.sysconfig import get_compile_flags as get_compile_flags, get_include as get_include, get_lib as get_lib, get_link_flags as get_link_flags
