# Stubs for tensorflow.contrib.seq2seq.ops.gen_beam_search_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def gather_tree(step_ids: Any, parent_ids: Any, max_sequence_lengths: Any, end_token: Any, name: Optional[Any] = ...): ...
def gather_tree_eager_fallback(step_ids: Any, parent_ids: Any, max_sequence_lengths: Any, end_token: Any, name: Optional[Any] = ..., ctx: Optional[Any] = ...): ...
