# Stubs for tensorflow._api.v1.saved_model.signature_def_utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.saved_model.signature_def_utils import build_signature_def as build_signature_def, classification_signature_def as classification_signature_def, is_valid_signature as is_valid_signature, predict_signature_def as predict_signature_def, regression_signature_def as regression_signature_def
