# Stubs for tensorflow.contrib.estimator.python.estimator.baseline (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.estimator import estimator as estimator
from tensorflow.python.estimator.canned import baseline as baseline
from typing import Any as Any, Optional as Optional

class BaselineEstimator(estimator.Estimator):
    def __init__(self, head: Any, model_dir: Optional[Any] = ..., optimizer: str = ..., config: Optional[Any] = ...) -> None: ...
