# Stubs for tensorflow.contrib.estimator.python.estimator.dnn (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.estimator import estimator as estimator
from tensorflow.python.ops import nn as nn
from typing import Any as Any, Optional as Optional

class DNNEstimator(estimator.Estimator):
    def __init__(self, head: Any, hidden_units: Any, feature_columns: Any, model_dir: Optional[Any] = ..., optimizer: str = ..., activation_fn: Any = ..., dropout: Optional[Any] = ..., input_layer_partitioner: Optional[Any] = ..., config: Optional[Any] = ..., warm_start_from: Optional[Any] = ..., batch_norm: bool = ...) -> None: ...
