# Stubs for tensorflow.contrib.estimator.python.estimator.dnn_linear_combined (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.estimator import estimator as estimator
from tensorflow.python.ops import nn as nn
from typing import Any as Any, Optional as Optional

class DNNLinearCombinedEstimator(estimator.Estimator):
    def __init__(self, head: Any, model_dir: Optional[Any] = ..., linear_feature_columns: Optional[Any] = ..., linear_optimizer: str = ..., dnn_feature_columns: Optional[Any] = ..., dnn_optimizer: str = ..., dnn_hidden_units: Optional[Any] = ..., dnn_activation_fn: Any = ..., dnn_dropout: Optional[Any] = ..., input_layer_partitioner: Optional[Any] = ..., config: Optional[Any] = ..., linear_sparse_combiner: str = ...) -> None: ...
