# Stubs for tensorflow.contrib.estimator.python.estimator.export (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any, Optional as Optional

def export_saved_model_for_mode(estimator: Any, export_dir_base: Any, input_receiver_fn: Any, assets_extra: Optional[Any] = ..., as_text: bool = ..., checkpoint_path: Optional[Any] = ..., strip_default_attrs: bool = ..., mode: Any = ...): ...
def export_all_saved_models(estimator: Any, export_dir_base: Any, input_receiver_fn_map: Any, assets_extra: Optional[Any] = ..., as_text: bool = ..., checkpoint_path: Optional[Any] = ..., strip_default_attrs: bool = ...): ...
