# Stubs for tensorflow.contrib.estimator.python.estimator.linear (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.estimator import estimator as estimator
from typing import Any as Any, Optional as Optional

class LinearEstimator(estimator.Estimator):
    def __init__(self, head: Any, feature_columns: Any, model_dir: Optional[Any] = ..., optimizer: str = ..., config: Optional[Any] = ..., partitioner: Optional[Any] = ..., sparse_combiner: str = ...) -> None: ...
