# Stubs for tensorflow.contrib.estimator.python.estimator.logit_fns (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.util import function_utils as function_utils
from typing import Any as Any

dnn_logit_fn_builder: Any
linear_logit_fn_builder: Any

def call_logit_fn(logit_fn: Any, features: Any, mode: Any, params: Any, config: Any): ...
