# Stubs for tensorflow.contrib.estimator.python.estimator.multi_head (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.estimator import model_fn as model_fn
from tensorflow.python.estimator.canned import head as head_lib, metric_keys as metric_keys
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, math_ops as math_ops
from tensorflow.python.saved_model import signature_constants as signature_constants
from tensorflow.python.summary import summary as summary
from tensorflow.python.training import training_util as training_util
from typing import Any as Any, Optional as Optional

def multi_head(heads: Any, head_weights: Optional[Any] = ...): ...

class _MultiHead(head_lib._Head):
    def __init__(self, heads: Any, head_weights: Any) -> None: ...
    @property
    def name(self): ...
    @property
    def logits_dimension(self): ...
    def create_loss(self, features: Any, mode: Any, logits: Any, labels: Any): ...
    def create_estimator_spec(self, features: Any, mode: Any, logits: Any, labels: Optional[Any] = ..., optimizer: Optional[Any] = ..., train_op_fn: Optional[Any] = ...): ...
