# Stubs for tensorflow.contrib.estimator.python.estimator.saved_model_estimator (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.estimator import estimator as estimator_lib
from tensorflow.python.estimator.export import export_output as export_output
from tensorflow.python.framework import dtypes as dtypes, ops as ops, tensor_shape as tensor_shape
from tensorflow.python.saved_model import constants as constants, loader_impl as loader_impl, signature_constants as signature_constants
from tensorflow.python.training import checkpoint_utils as checkpoint_utils, monitored_session as monitored_session, training_util as training_util
from typing import Any as Any, Optional as Optional

class SavedModelEstimator(estimator_lib.Estimator):
    saved_model_dir: Any = ...
    saved_model_loader: Any = ...
    def __init__(self, saved_model_dir: Any, model_dir: Optional[Any] = ...) -> None: ...
