# Stubs for tensorflow.contrib.kafka (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.kafka.python.ops.kafka_dataset_ops import KafkaDataset as KafkaDataset
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
