# Stubs for tensorflow.contrib.rpc.python.ops.rpc_op (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.rpc.python.ops.gen_rpc_op import rpc as rpc, try_rpc as try_rpc
from tensorflow.python.framework import ops as ops
