# Stubs for tensorflow.core.debug.debugger_event_metadata_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
DebuggerEventMetadata: Any
