# Stubs for tensorflow.contrib.kinesis (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.kinesis.python.ops.kinesis_dataset_ops import KinesisDataset as KinesisDataset
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
