# Stubs for tensorflow.core.example.example_parser_configuration_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
VarLenFeatureProto: Any
FixedLenFeatureProto: Any
FeatureConfiguration: Any
ExampleParserConfiguration: Any
