# Stubs for tensorflow.python.training.basic_loops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import errors as errors
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

def basic_train_loop(supervisor: Any, train_step_fn: Any, args: Optional[Any] = ..., kwargs: Optional[Any] = ..., master: str = ...) -> None: ...
