# Stubs for tensorflow.python.training.queue_runner (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.training.queue_runner_impl import *
