# Stubs for tensorflow.python.training.training_util (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.eager import context as context
from tensorflow.python.framework import dtypes as dtypes, graph_io as graph_io, ops as ops
from tensorflow.python.ops import init_ops as init_ops, resource_variable_ops as resource_variable_ops, state_ops as state_ops, variable_scope as variable_scope, variables as variables
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

GLOBAL_STEP_READ_KEY: str
write_graph = graph_io.write_graph

def global_step(sess: Any, global_step_tensor: Any): ...
def get_global_step(graph: Optional[Any] = ...): ...
def create_global_step(graph: Optional[Any] = ...): ...
def get_or_create_global_step(graph: Optional[Any] = ...): ...
def assert_global_step(global_step_tensor: Any) -> None: ...
