# Stubs for tensorflow.contrib.nn.python.ops.cross_entropy (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops import nn as nn
from typing import Any as Any, Optional as Optional

def deprecated_flipped_softmax_cross_entropy_with_logits(logits: Any, labels: Any, dim: int = ..., name: Optional[Any] = ...): ...
def deprecated_flipped_sparse_softmax_cross_entropy_with_logits(logits: Any, labels: Any, name: Optional[Any] = ...): ...
def deprecated_flipped_sigmoid_cross_entropy_with_logits(logits: Any, targets: Any, name: Optional[Any] = ...): ...
