# Stubs for tensorflow.contrib.nn.python.ops.fwd_gradients (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops
from tensorflow.python.ops.gradients_impl import gradients as gradients
from typing import Any as Any, Optional as Optional

def fwd_gradients(ys: Any, xs: Any, grad_xs: Optional[Any] = ..., assert_unused: bool = ...): ...
