# Stubs for tensorflow.contrib.nearest_neighbor.python.ops.nearest_neighbor_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.util import loader as loader
from tensorflow.python.framework import ops as ops
from tensorflow.python.platform import resource_loader as resource_loader
from typing import Any as Any, Optional as Optional

def hyperplane_lsh_probes(point_hyperplane_product: Any, num_tables: Any, num_hyperplanes_per_table: Any, num_probes: Any, name: Optional[Any] = ...): ...
