# Stubs for tensorflow.core.protobuf.config_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
GPUOptions: Any
OptimizerOptions: Any
GraphOptions: Any
ThreadPoolOptionProto: Any
RPCOptions: Any
ConfigProto: Any
RunOptions: Any
RunMetadata: Any
TensorConnection: Any
CallableOptions: Any
