# Stubs for tensorflow.core.protobuf.debug_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
DebugTensorWatch: Any
DebugOptions: Any
DebuggedSourceFile: Any
DebuggedSourceFiles: Any
