# Stubs for tensorflow.core.protobuf.tensorflow_server_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
ServerDef: Any
