# Stubs for tensorflow.core.protobuf.tensor_bundle_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
BundleHeaderProto: Any
BundleEntryProto: Any
