# Stubs for tensorflow.contrib.gan.python.estimator.python.gan_estimator (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.gan.python.estimator.python.gan_estimator_impl import *
from tensorflow.contrib.gan.python.estimator.python import gan_estimator_impl as gan_estimator_impl
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented

# Names in __all__ with no definition:
#   GANEstimator
#   SummaryType
