# Stubs for tensorflow.python.data.kernel_tests.test_base (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.data.util import nest as nest
from tensorflow.python.eager import context as context
from tensorflow.python.framework import errors as errors, sparse_tensor as sparse_tensor
from tensorflow.python.platform import test as test
from typing import Any as Any, Optional as Optional

class DatasetTestBase(test.TestCase):
    def assertSparseValuesEqual(self, a: Any, b: Any) -> None: ...
    def getNext(self, dataset: Any): ...
    def assertDatasetsEqual(self, dataset1: Any, dataset2: Any) -> None: ...
    def assertDatasetsRaiseSameError(self, dataset1: Any, dataset2: Any, exception_class: Any, replacements: Optional[Any] = ...) -> None: ...
