# Stubs for tensorflow.linalg (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python import cholesky as cholesky, cholesky_solve as cholesky_solve, cross as cross, einsum as einsum, eye as eye, global_norm as global_norm, matmul as matmul, norm as norm, qr as qr, svd as svd, tensordot as tensordot, trace as trace
from tensorflow.python.ops.linalg.linalg import LinearOperator as LinearOperator, LinearOperatorBlockDiag as LinearOperatorBlockDiag, LinearOperatorCirculant as LinearOperatorCirculant, LinearOperatorCirculant2D as LinearOperatorCirculant2D, LinearOperatorCirculant3D as LinearOperatorCirculant3D, LinearOperatorComposition as LinearOperatorComposition, LinearOperatorDiag as LinearOperatorDiag, LinearOperatorFullMatrix as LinearOperatorFullMatrix, LinearOperatorIdentity as LinearOperatorIdentity, LinearOperatorKronecker as LinearOperatorKronecker, LinearOperatorLowRankUpdate as LinearOperatorLowRankUpdate, LinearOperatorLowerTriangular as LinearOperatorLowerTriangular, LinearOperatorScaledIdentity as LinearOperatorScaledIdentity, LinearOperatorZeros as LinearOperatorZeros, adjoint as adjoint, logdet as logdet
from tensorflow.python.ops.nn import l2_normalize as l2_normalize
