# Stubs for tensorflow.python.keras.wrappers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.wrappers import scikit_learn as scikit_learn
