# Stubs for tensorflow.contrib.coder.python.ops.coder_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.coder.python.ops.gen_coder_ops import *
from tensorflow.contrib.coder.python.ops import gen_coder_ops as gen_coder_ops
from tensorflow.contrib.util import loader as loader
from tensorflow.python.platform import resource_loader as resource_loader
