# Stubs for tensorflow.python.autograph.pyct.parser (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util import tf_inspect as tf_inspect
from typing import Any as Any

def parse_entity(entity: Any): ...
def parse_str(src: Any): ...
def parse_expression(src: Any): ...
