# Stubs for tensorflow.initializers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python import he_normal as he_normal, he_uniform as he_uniform, lecun_normal as lecun_normal, lecun_uniform as lecun_uniform, tables_initializer as tables_initializer
