# Stubs for tensorflow.contrib.copy_graph (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.copy_graph.python.util.copy_elements import *
from tensorflow.contrib.copy_graph.python.util import copy_elements as copy_elements
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
