# Stubs for tensorflow.python.ops.linalg.linear_operator_low_rank_update (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, linalg_ops as linalg_ops, math_ops as math_ops
from tensorflow.python.ops.linalg import linear_operator as linear_operator, linear_operator_diag as linear_operator_diag, linear_operator_identity as linear_operator_identity, linear_operator_util as linear_operator_util
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any, Optional as Optional

class LinearOperatorLowRankUpdate(linear_operator.LinearOperator):
    def __init__(self, base_operator: Any, u: Any, diag_update: Optional[Any] = ..., v: Optional[Any] = ..., is_diag_update_positive: Optional[Any] = ..., is_non_singular: Optional[Any] = ..., is_self_adjoint: Optional[Any] = ..., is_positive_definite: Optional[Any] = ..., is_square: Optional[Any] = ..., name: str = ...) -> None: ...
    @property
    def u(self): ...
    @property
    def v(self): ...
    @property
    def is_diag_update_positive(self): ...
    @property
    def diag_update(self): ...
    @property
    def diag_operator(self): ...
    @property
    def base_operator(self): ...
