# Stubs for tensorflow.contrib.decision_trees (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.decision_trees.proto import *
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
