# Stubs for tensorflow.contrib.timeseries.python.timeseries.model_utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.timeseries.python.timeseries import feature_keys as feature_keys
from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import init_ops as init_ops, nn_ops as nn_ops, variable_scope as variable_scope
from typing import Any as Any

def fully_connected(inp: Any, inp_size: Any, layer_size: Any, name: Any, activation: Any = ..., dtype: Any = ...): ...
def parameter_switch(parameter_overrides: Any): ...
def canonicalize_times_or_steps_from_output(times: Any, steps: Any, previous_model_output: Any): ...
