# Stubs for tensorflow.python.autograph.converters.continue_statements (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.autograph.core import converter as converter
from tensorflow.python.autograph.pyct import anno as anno, templates as templates
from tensorflow.python.autograph.pyct.static_analysis.annos import NodeAnno as NodeAnno
from typing import Any as Any

CONTROL_VAR_NAME: str
CONTINUE_USED: str
GUARD_CREATED: str
CREATE_GUARD_NEXT: str

class ContinueCanonicalizationTransformer(converter.Base):
    def visit_Continue(self, node: Any): ...
    def visit_While(self, node: Any): ...
    def visit_For(self, node: Any): ...
    def visit_If(self, node: Any): ...
    def visit_With(self, node: Any): ...

def transform(node: Any, ctx: Any): ...
