# Stubs for tensorflow.python.autograph.converters.function_scopes (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.autograph.core import converter as converter
from tensorflow.python.autograph.pyct import templates as templates
from typing import Any as Any

class FunctionBodyTransformer(converter.Base):
    def visit_FunctionDef(self, node: Any): ...

def transform(node: Any, ctx: Any): ...
