# Stubs for tensorflow.contrib.cloud.python.ops.bigquery_reader_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.cloud.python.ops import gen_bigquery_reader_ops as gen_bigquery_reader_ops
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import io_ops as io_ops
from typing import Any as Any, Optional as Optional

class BigQueryReader(io_ops.ReaderBase):
    def __init__(self, project_id: Any, dataset_id: Any, table_id: Any, timestamp_millis: Any, num_partitions: Any, features: Optional[Any] = ..., columns: Optional[Any] = ..., test_end_point: Optional[Any] = ..., name: Optional[Any] = ...) -> None: ...
    def partitions(self, name: Optional[Any] = ...): ...
