# Stubs for tensorflow.contrib.linear_optimizer.python.ops.sparse_feature_column (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes
from tensorflow.python.framework.ops import internal_convert_to_tensor as internal_convert_to_tensor, name_scope as name_scope
from typing import Any as Any

class SparseFeatureColumn:
    def __init__(self, example_indices: Any, feature_indices: Any, feature_values: Any) -> None: ...
    @property
    def example_indices(self): ...
    @property
    def feature_indices(self): ...
    @property
    def feature_values(self): ...
