# Stubs for tensorflow.contrib.gan.python.losses (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.gan.python.losses.python.tuple_losses import *
from tensorflow.contrib.gan.python.losses.python import tuple_losses as tuple_losses
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
