# Stubs for tensorflow.contrib.legacy_seq2seq (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.legacy_seq2seq.python.ops.seq2seq import attention_decoder as attention_decoder, basic_rnn_seq2seq as basic_rnn_seq2seq, embedding_attention_decoder as embedding_attention_decoder, embedding_attention_seq2seq as embedding_attention_seq2seq, embedding_rnn_decoder as embedding_rnn_decoder, embedding_rnn_seq2seq as embedding_rnn_seq2seq, embedding_tied_rnn_seq2seq as embedding_tied_rnn_seq2seq, model_with_buckets as model_with_buckets, one2many_rnn_seq2seq as one2many_rnn_seq2seq, rnn_decoder as rnn_decoder, sequence_loss as sequence_loss, sequence_loss_by_example as sequence_loss_by_example, tied_rnn_seq2seq as tied_rnn_seq2seq
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
