# Stubs for tensorflow.contrib.saved_model.python.saved_model.reader (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.core.protobuf import saved_model_pb2 as saved_model_pb2
from tensorflow.python.lib.io import file_io as file_io
from tensorflow.python.saved_model import constants as constants
from tensorflow.python.util import compat as compat
from typing import Any as Any

def read_saved_model(saved_model_dir: Any): ...
def get_saved_model_tag_sets(saved_model_dir: Any): ...
