# Stubs for tensorflow.contrib.labeled_tensor (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.labeled_tensor.python.ops import core as _core, io_ops as _io_ops, nn as nn, ops as _ops, sugar as _sugar
from typing import Any as Any

Axis = _core.Axis
Axes = _core.Axes
LabeledTensor = _core.LabeledTensor
as_axis = _core.as_axis
convert_to_labeled_tensor = _core.convert_to_labeled_tensor
identity = _core.identity
slice = _core.slice_function
transpose = _core.transpose
expand_dims = _core.expand_dims
align = _core.align
axis_order_scope = _core.axis_order_scope
check_axis_order = _core.check_axis_order
impose_axis_order = _core.impose_axis_order
AxisOrderError = _core.AxisOrderError
define_unary_op = _core.define_unary_op
define_binary_op = _core.define_binary_op
define_reduce_op = _ops.define_reduce_op
abs: Any
neg: Any
sign: Any
reciprocal: Any
square: Any
round: Any
sqrt: Any
rsqrt: Any
exp: Any
log: Any
ceil: Any
floor: Any
cos: Any
sin: Any
tan: Any
acos: Any
asin: Any
atan: Any
lgamma: Any
digamma: Any
erf: Any
erfc: Any
logical_not: Any
tanh: Any
sigmoid: Any
add: Any
sub: Any
mul: Any
div: Any
mod: Any
pow: Any
equal: Any
greater: Any
greater_equal: Any
not_equal: Any
less: Any
less_equal: Any
logical_and: Any
logical_or: Any
logical_xor: Any
maximum: Any
minimum: Any
squared_difference: Any
igamma: Any
igammac: Any
zeta: Any
polygamma: Any
select = _ops.select
concat = _ops.concat
pack = _ops.pack
unpack = _ops.unpack
reshape = _ops.reshape
rename_axis = _ops.rename_axis
random_crop = _ops.random_crop
map_fn = _ops.map_fn
foldl = _ops.foldl
squeeze = _ops.squeeze
matmul = _ops.matmul
tile = _ops.tile
pad = _ops.pad
constant = _ops.constant
zeros_like = _ops.zeros_like
ones_like = _ops.ones_like
cast = _ops.cast
verify_tensor_all_finite = _ops.verify_tensor_all_finite
boolean_mask = _ops.boolean_mask
where = _ops.where
reduce_all: Any
reduce_any: Any
reduce_logsumexp: Any
reduce_max: Any
reduce_mean: Any
reduce_min: Any
reduce_prod: Any
reduce_sum: Any
batch = _ops.batch
shuffle_batch = _ops.shuffle_batch
FixedLenFeature = _io_ops.FixedLenFeature
parse_example = _io_ops.parse_example
parse_single_example = _io_ops.parse_single_example
placeholder = _io_ops.placeholder
ReshapeCoder = _sugar.ReshapeCoder
