# Stubs for tensorflow.contrib.gan (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.gan.python.namedtuples import *
from tensorflow.contrib.gan.python.train import *
from tensorflow.contrib.gan.python import estimator as estimator, eval as eval, features as features, losses as losses, namedtuples as namedtuples, train as train
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
