# Stubs for tensorflow.python.training.slot_creator (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.eager import context as context
from tensorflow.python.ops import array_ops as array_ops, init_ops as init_ops, resource_variable_ops as resource_variable_ops, variable_scope as variable_scope, variables as variables
from tensorflow.python.training import distribution_strategy_context as distribution_strategy_context
from typing import Any as Any, Optional as Optional

def create_slot(primary: Any, val: Any, name: Any, colocate_with_primary: bool = ...): ...
def create_slot_with_initializer(primary: Any, initializer: Any, shape: Any, dtype: Any, name: Any, colocate_with_primary: bool = ...): ...
def create_zeros_slot(primary: Any, name: Any, dtype: Optional[Any] = ..., colocate_with_primary: bool = ...): ...
