# Stubs for tensorflow.python.training.training_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.training.gen_training_ops import *
from tensorflow.python.training import gen_training_ops as gen_training_ops
