# Stubs for tensorflow.python.ops.parallel_for.control_flow_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, tensor_array_ops as tensor_array_ops
from tensorflow.python.ops.parallel_for.pfor import PFor as PFor
from tensorflow.python.util import nest as nest
from typing import Any as Any

def for_loop(loop_fn: Any, loop_fn_dtypes: Any, iters: Any): ...
def pfor(loop_fn: Any, iters: Any): ...
