# Stubs for tensorflow.contrib.nearest_neighbor (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.nearest_neighbor.python.ops.nearest_neighbor_ops import *
