# Stubs for tensorflow.gfile (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.platform.gfile import FastGFile as FastGFile, GFile as GFile
