# Stubs for tensorflow.contrib.slim.python.slim.nets.alexnet (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib import layers as layers
from tensorflow.contrib.framework.python.ops import arg_scope as arg_scope
from tensorflow.contrib.layers.python.layers import regularizers as regularizers, utils as utils
from tensorflow.python.ops import array_ops as array_ops, init_ops as init_ops, nn_ops as nn_ops, variable_scope as variable_scope
from typing import Any as Any

trunc_normal: Any

def alexnet_v2_arg_scope(weight_decay: float = ...): ...
def alexnet_v2(inputs: Any, num_classes: int = ..., is_training: bool = ..., dropout_keep_prob: float = ..., spatial_squeeze: bool = ..., scope: str = ...): ...
