# Stubs for tensorflow.contrib.slim.python.slim.nets.inception_v1 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib import layers as layers
from tensorflow.contrib.framework.python.ops import arg_scope as arg_scope
from tensorflow.contrib.layers.python.layers import initializers as initializers, regularizers as regularizers
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, init_ops as init_ops, nn_ops as nn_ops, variable_scope as variable_scope
from typing import Any as Any, Optional as Optional

trunc_normal: Any

def inception_v1_base(inputs: Any, final_endpoint: str = ..., scope: str = ...): ...
def inception_v1(inputs: Any, num_classes: int = ..., is_training: bool = ..., dropout_keep_prob: float = ..., prediction_fn: Any = ..., spatial_squeeze: bool = ..., reuse: Optional[Any] = ..., scope: str = ...): ...
def inception_v1_arg_scope(weight_decay: float = ..., use_batch_norm: bool = ..., batch_norm_var_collection: str = ...): ...
