# Stubs for tensorflow.contrib.quantization (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.quantization.python.math_ops import *
from tensorflow.contrib.quantization.python.nn_ops import *
from tensorflow.python.ops.gen_array_ops import dequantize as dequantize, quantize_v2 as quantize_v2, quantized_concat as quantized_concat
