# Stubs for tensorflow.contrib.learn.python.learn.learn_io.dask_io (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util.deprecation import deprecated as deprecated
from typing import Any as Any

allowed_classes: Any
HAS_DASK: bool

def extract_dask_data(data: Any): ...
def extract_dask_labels(labels: Any): ...
