# Stubs for tensorflow.python.compat.compat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.util import tf_contextlib as tf_contextlib
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

def forward_compatible(year: Any, month: Any, day: Any): ...
def forward_compatibility_horizon(year: Any, month: Any, day: Any) -> None: ...
