# Stubs for tensorflow.contrib.sparsemax.python.ops.sparsemax_loss (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops
from typing import Any as Any, Optional as Optional

def sparsemax_loss(logits: Any, sparsemax: Any, labels: Any, name: Optional[Any] = ...): ...
