# Stubs for tensorflow.contrib.sparsemax.python.ops.sparsemax (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops, nn as nn
from typing import Any as Any, Optional as Optional

def sparsemax(logits: Any, name: Optional[Any] = ...): ...
