# Stubs for tensorflow.python.platform.status_bar (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

def SetupStatusBarInsideGoogle(unused_link_text: Any, unused_port: Any) -> None: ...
