# Stubs for tensorflow.contrib.checkpoint.python.python_state (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import abc as abc
from tensorflow.python.training.checkpointable import base as base
from typing import Any as Any

class NumpyState(base.CheckpointableBase):
    def __getattribute__(self, name: Any): ...
    def __setattr__(self, name: Any, value: Any) -> None: ...

class PythonStateWrapper(base.CheckpointableBase, metaclass=abc.ABCMeta): ...

class _NumpyWrapper(PythonStateWrapper):
    array: Any = ...
    def __init__(self, array: Any) -> None: ...
