# Stubs for tensorflow.contrib.checkpoint.python.split_dependency (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops import control_flow_ops as control_flow_ops
from tensorflow.python.training import saver as saver_lib
from tensorflow.python.training.checkpointable import base as checkpointable
from typing import Any as Any

class _CallbackSaveable(saver_lib.BaseSaverBuilder.SaveableObject):
    def __init__(self, name: Any, dtype: Any, save_callback: Any, restore_callback: Any) -> None: ...
    def restore(self, restored_tensors: Any, restored_shapes: Any): ...

class _SplitDependency(checkpointable.CheckpointableBase):
    def __init__(self, save_buffer: Any, restore_buffer: Any, name: Any, dtype: Any, num_components: Any, fill_save_buffer_fn: Any, consume_restore_buffer_fn: Any) -> None: ...

def split_dependency(component_names: Any, component_dtypes: Any, fill_save_buffer_fn: Any, consume_restore_buffer_fn: Any): ...
