# Stubs for tensorflow.contrib.checkpoint.python.visualize (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python import pywrap_tensorflow as pywrap_tensorflow
from typing import Any as Any

def dot_graph_from_checkpoint(save_path: Any): ...
