# Stubs for tensorflow.contrib.sparsemax (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.sparsemax.python.ops.sparsemax import sparsemax as sparsemax
from tensorflow.contrib.sparsemax.python.ops.sparsemax_loss import sparsemax_loss as sparsemax_loss
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
