# Stubs for tensorflow.contrib.boosted_trees.proto.learner_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
TreeRegularizationConfig: Any
TreeConstraintsConfig: Any
LearningRateConfig: Any
LearningRateFixedConfig: Any
LearningRateLineSearchConfig: Any
AveragingConfig: Any
LearningRateDropoutDrivenConfig: Any
LearnerConfig: Any
