# Stubs for tensorflow.contrib.boosted_trees.proto.quantiles_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
QuantileConfig: Any
QuantileEntry: Any
QuantileSummaryState: Any
QuantileStreamState: Any
