# Stubs for tensorflow._api.v1.sets (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops.sets import set_difference as set_difference, set_intersection as set_intersection, set_size as set_size, set_union as set_union
