# Stubs for tensorflow.contrib.layers.python.ops.sparse_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.framework import dtypes as dtypes, ops as ops, sparse_tensor as sparse_tensor
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops
from tensorflow.python.util import compat as compat
from typing import Any as Any, Optional as Optional

def dense_to_sparse_tensor(dense_tensor: Any, ignore_value: Optional[Any] = ...): ...
def indicators_to_sparse_ids(indicators: Any, ignore_value: Optional[Any] = ..., dtype: Any = ...): ...
def sparse_row_envelope(sparse_input: Any, row_axis: int = ..., col_axis: int = ..., name: Optional[Any] = ...): ...
