# Stubs for tensorflow.contrib.layers.python.ops.sparse_feature_cross_op (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.framework import deprecated_arg_values as deprecated_arg_values
from tensorflow.contrib.layers.ops import gen_sparse_feature_cross_op as gen_sparse_feature_cross_op
from tensorflow.contrib.util import loader as loader
from tensorflow.python.framework import dtypes as dtypes, ops as ops, sparse_tensor as sparse_tensor
from tensorflow.python.ops import math_ops as math_ops
from tensorflow.python.platform import resource_loader as resource_loader
from typing import Any as Any, Optional as Optional

SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY: int

def sparse_feature_cross(inputs: Any, hashed_output: bool = ..., num_buckets: int = ..., name: Optional[Any] = ..., hash_key: Optional[Any] = ...): ...
