# Stubs for tensorflow.contrib.memory_stats (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.memory_stats.python.ops.memory_stats_ops import BytesInUse as BytesInUse, BytesLimit as BytesLimit, MaxBytesInUse as MaxBytesInUse
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
