# Stubs for tensorflow.contrib.staging (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.ops.data_flow_ops import StagingArea as StagingArea
