# Stubs for tensorflow.contrib.remote_fused_graph.pylib.python.ops.remote_fused_graph_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.remote_fused_graph.pylib.python.ops import gen_remote_fused_graph_ops as gen_remote_fused_graph_ops
from tensorflow.python.framework import dtypes as dtypes, ops as ops
from typing import Any as Any, Optional as Optional

def remote_fused_graph_execute(inputs: Any, output_types: Any, graph_def: Any, graph_input_node_names: Any, graph_output_node_names: Any, executor_name: Any, serialized_executor_parameters: Any, default_graph_input_tensor_type_shapes: Optional[Any] = ..., default_graph_output_tensor_type_shapes: Optional[Any] = ...): ...
