# Stubs for tensorflow.python.distribute.estimator_training (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.training import server_lib as server_lib
from typing import Any as Any

CHIEF: Any
EVALUATOR: Any
PS: Any
WORKER: Any

def init_run_config(config: Any, tf_config: Any) -> None: ...
def should_run_distribute_coordinator(config: Any): ...
def train_and_evaluate(estimator: Any, train_spec: Any, eval_spec: Any, executor_cls: Any) -> None: ...
