# Stubs for tensorflow._api.v1.keras.applications.mobilenet_v2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python.keras.applications import MobileNetV2 as MobileNetV2
from tensorflow.python.keras.applications.mobilenet_v2 import decode_predictions as decode_predictions, preprocess_input as preprocess_input
