# Stubs for tensorflow.contrib.libsvm.python.ops.libsvm_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.libsvm.ops import gen_libsvm_ops as gen_libsvm_ops
from tensorflow.contrib.util import loader as loader
from tensorflow.python.framework import ops as ops, sparse_tensor as sparse_tensor
from tensorflow.python.platform import resource_loader as resource_loader
from typing import Any as Any, Optional as Optional

def decode_libsvm(content: Any, num_features: Any, dtype: Optional[Any] = ..., label_dtype: Optional[Any] = ...): ...
