# Stubs for tensorflow.core.kernels.boosted_trees.boosted_trees_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
Node: Any
NodeMetadata: Any
Leaf: Any
Vector: Any
SparseVector: Any
BucketizedSplit: Any
CategoricalSplit: Any
Tree: Any
TreeMetadata: Any
GrowingMetadata: Any
TreeEnsemble: Any
DebugOutput: Any
