# Stubs for tensorflow.contrib.predictor (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.predictor.predictor_factories import from_contrib_estimator as from_contrib_estimator, from_estimator as from_estimator, from_saved_model as from_saved_model
from tensorflow.python.util.all_util import remove_undocumented as remove_undocumented
