# Stubs for tensorflow.contrib.predictor.contrib_estimator_predictor (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.learn.python.learn.utils import saved_model_export_utils as saved_model_export_utils
from tensorflow.contrib.predictor import predictor as predictor
from tensorflow.python.framework import ops as ops
from tensorflow.python.training import checkpoint_management as checkpoint_management, monitored_session as monitored_session
from typing import Any as Any, Optional as Optional

class ContribEstimatorPredictor(predictor.Predictor):
    def __init__(self, estimator: Any, prediction_input_fn: Any, input_alternative_key: Optional[Any] = ..., output_alternative_key: Optional[Any] = ..., graph: Optional[Any] = ..., config: Optional[Any] = ...) -> None: ...
