# Stubs for tensorflow.contrib.predictor.predictor (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import abc as abc
from typing import Any as Any

class Predictor(metaclass=abc.ABCMeta):
    @property
    def graph(self): ...
    @property
    def session(self): ...
    @property
    def feed_tensors(self): ...
    @property
    def fetch_tensors(self): ...
    def __call__(self, input_dict: Any): ...
