# Stubs for tensorflow.contrib.predictor.saved_model_predictor (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.contrib.predictor import predictor as predictor
from tensorflow.contrib.saved_model.python.saved_model import reader as reader
from tensorflow.python.client import session as session
from tensorflow.python.framework import ops as ops
from tensorflow.python.saved_model import loader as loader, signature_constants as signature_constants
from typing import Any as Any, Optional as Optional

DEFAULT_TAGS: str

def get_meta_graph_def(saved_model_dir: Any, tags: Any): ...

class SavedModelPredictor(predictor.Predictor):
    def __init__(self, export_dir: Any, signature_def_key: Optional[Any] = ..., signature_def: Optional[Any] = ..., input_names: Optional[Any] = ..., output_names: Optional[Any] = ..., tags: Optional[Any] = ..., graph: Optional[Any] = ..., config: Optional[Any] = ...) -> None: ...
