# Stubs for tensorflow.core.util.memmapped_file_system_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
MemmappedFileSystemDirectoryElement: Any
MemmappedFileSystemDirectory: Any
