# Stubs for tensorflow.core.util.test_log_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
EntryValue: Any
BenchmarkEntry: Any
BenchmarkEntries: Any
BuildConfiguration: Any
CommitId: Any
CPUInfo: Any
MemoryInfo: Any
GPUInfo: Any
PlatformInfo: Any
AvailableDeviceInfo: Any
MachineConfiguration: Any
RunConfiguration: Any
TestResults: Any
