# Stubs for tensorflow.core.lib.core.error_codes_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as Any

DESCRIPTOR: Any
Code: Any
OK: int
CANCELLED: int
UNKNOWN: int
INVALID_ARGUMENT: int
DEADLINE_EXCEEDED: int
NOT_FOUND: int
ALREADY_EXISTS: int
PERMISSION_DENIED: int
UNAUTHENTICATED: int
RESOURCE_EXHAUSTED: int
FAILED_PRECONDITION: int
ABORTED: int
OUT_OF_RANGE: int
UNIMPLEMENTED: int
INTERNAL: int
UNAVAILABLE: int
DATA_LOSS: int
DO_NOT_USE_RESERVED_FOR_FUTURE_EXPANSION_USE_DEFAULT_IN_SWITCH_INSTEAD_: int
